# Generated by Django 5.1.4 on 2025-06-25 13:28

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations
from django.db import models

import account.mixins
import account.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "business_account_type",
                    models.CharField(
                        choices=[
                            ("SELLER", "Seller"),
                            ("JEWELER", "Jeweler"),
                            ("INVESTOR", "Investor"),
                            ("MANUFACTURER", "Manufacturer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "business_original_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "musharakah_client_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GROWTH", "Growth"),
                            ("REPUTABLE", "Reputable"),
                        ],
                        default="NEW",
                        help_text="Select the business type",
                        max_length=25,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("ESTABLISHMENT", "Establishment"),
                            ("WLL", "WLL (With Limited Liability)"),
                        ],
                        default="ESTABLISHMENT",
                        help_text="The legal structure or type of the business.",
                        max_length=50,
                    ),
                ),
                ("is_existing_business", models.BooleanField(default=False)),
                ("logo", models.CharField(blank=True, max_length=500, null=True)),
                ("is_suspended", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Business Account",
                "verbose_name_plural": "Business Accounts",
                "db_table": "business_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CountryToContinent",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("continent", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.000"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Tax rate as a decimal (e.g., 0.05 for 5%)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "platform_fee_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT rate as a decimal (e.g., 0.15 for 15%)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "additional_fee",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=22,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("PAYMENT", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transfer_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BENEFIT_PAY", "Benefit Pay"),
                            ("CREDIMAX", "Credimax"),
                            ("ORGANIZATION_ADMIN", "Organization Admin"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="BHD", max_length=20)),
                (
                    "benefit_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "benefit_result",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("benefit_response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
            },
            bases=(models.Model, account.mixins.ReceiptNumberMixin),
        ),
        migrations.CreateModel(
            name="TransactionAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attachment", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Transaction Attachment",
                "verbose_name_plural": "Transaction Attachments",
                "db_table": "transaction_attachments",
            },
        ),
        migrations.CreateModel(
            name="UserAssignedBusiness",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_owner", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User Assigned Business",
                "verbose_name_plural": "User Assigned Businesses",
                "db_table": "user_assigned_businesses",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")],
                        default="en",
                        help_text="Select the user's language preference.",
                        max_length=2,
                        verbose_name="Language Preference",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="The user's preferred timezone.",
                        max_length=255,
                        null=True,
                        verbose_name="Timezone",
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("emails_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WebhookCall",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "transfer_via",
                    models.CharField(
                        choices=[
                            ("BENEFIT_PAY", "Benefit Pay"),
                            ("CREDIMAX", "Credimax"),
                            ("ORGANIZATION_ADMIN", "Organization Admin"),
                        ],
                        default="BENEFIT_PAY",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment"),
                            ("REFUND", "Refund"),
                            ("OTHERS", "Others"),
                            ("AUTHENTICATION", "Authentication"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("request_body", models.JSONField()),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Webhook Call",
                "verbose_name_plural": "Webhook Calls",
                "db_table": "webhook_calls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Enter the user's phone number in international format.",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                (
                    "phone_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                            ("SUSPEND", "Suspend"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        help_text="Select the user's status.",
                        max_length=20,
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "suspended_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIN", "Admin"),
                            ("BUSINESS_OWNER", "Business Owner"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "access_token_expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="All access tokens issued before this time will be considered expired.",
                        null=True,
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(
                        blank=True,
                        help_text="The delete reason for the deletion of account.",
                        null=True,
                    ),
                ),
                ("face_verified", models.BooleanField(default=False)),
                ("document_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("individual_aml_verified", models.BooleanField(default=False)),
                ("business_aml_verified", models.BooleanField(default=False)),
                ("due_diligence_verified", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("address_line", models.CharField(max_length=255)),
                ("pincode", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("nationality", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="AdminUserRole",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("TAQABETH_ENFORCER", "Taqabeth Enforcer"),
                            ("JEWELLERY_INSPECTOR", "Jewellery Inspector"),
                            ("JEWELLERY_BUYER", "Jewellery Buyer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Admin User Role",
                "verbose_name_plural": "Organization Admin User Roles",
                "db_table": "organization_admin_user_roles",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="The name of the bank where the account is held.",
                        max_length=255,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="The bank account number of the user.", max_length=50
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="The name associated with the bank account.",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user to whom this bank account belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "bank_accounts",
            },
        ),
        migrations.CreateModel(
            name="BusinessAccountDocument",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("CR_CERTIFICATE", "CR Certificate"),
                            ("VAT_CERTIFICATE", "VAT Certificate"),
                            ("AUTHORIZATION_LETTER", "Authorization Letter"),
                        ],
                        help_text="Select the business document type",
                        max_length=25,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_documents",
                        to="account.businessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "BusinessDocument",
                "verbose_name_plural": "BusinessDocuments",
                "db_table": "business_documents",
            },
        ),
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="An identifier provided by the user's device.",
                        max_length=255,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("WEB", "Web"),
                        ],
                        help_text="The type of device (e.g., Android, iOS, Web).",
                        max_length=50,
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        blank=True,
                        help_text="The FCM token used for sending push notifications.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Token",
                "verbose_name_plural": "FCM Tokens",
                "db_table": "fcm_tokens",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "commercial_registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vat_account_number",
                    models.CharField(
                        blank=True,
                        help_text="VAT account number for the organization",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(max_length=255, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Tax rate as a decimal (e.g., 0.05 for 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "platform_fee_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("AMOUNT", "Amount")],
                        default="PERCENTAGE",
                        help_text="Select the platform fee type (percentage or amount).",
                        max_length=12,
                    ),
                ),
                (
                    "platform_fee_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Platform fee rate as a decimal (e.g., 0.10 for 10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "platform_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Fixed platform fee amount (used when fee type is amount)",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="VAT rate as a decimal (e.g., 0.15 for 15%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                ("logo", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="ContactSupportRequest",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("query", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_supports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="account.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="account.organization",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationCurrency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("currency_code", models.CharField(max_length=10)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Currency",
                "verbose_name_plural": "Organization Currencies",
                "db_table": "organization_currencies",
            },
        ),
        migrations.CreateModel(
            name="RoleHistory",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("TAQABETH_ENFORCER", "Taqabeth Enforcer"),
                            ("JEWELLERY_INSPECTOR", "Jewellery Inspector"),
                            ("JEWELLERY_BUYER", "Jewellery Buyer"),
                            ("SELLER", "Seller"),
                            ("JEWELER", "Jeweler"),
                            ("INVESTOR", "Investor"),
                            ("MANUFACTURER", "Manufacturer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role History",
                "verbose_name_plural": "Role Histories",
                "db_table": "role_histories",
            },
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the entity.", max_length=255
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Director"),
                            ("AUTHORIZED_SIGNATORY", "Authorized Signatory"),
                            ("SHAREHOLDER", "Shareholder"),
                        ],
                        default="SHAREHOLDER",
                        help_text="The role of the shareholder in the business.",
                        max_length=25,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="The position held by the shareholder, if applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "id_document",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="The business to which this shareholder is associated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders",
                        to="account.businessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Holder",
                "verbose_name_plural": "Share Holders",
                "db_table": "share_holders",
            },
        ),
    ]
