# Generated by Django 5.1.4 on 2025-06-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("investor", "0002_initial"),
        ("jeweler", "0001_initial"),
        ("sooq_althahab_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="business_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="sooq_althahab_admin.businesssubscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="from_business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_from",
                to="account.businessaccount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="manufacturing_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="jeweler.manufacturingrequest",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="purchase_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="investor.purchaserequest",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_to",
                to="account.businessaccount",
            ),
        ),
        migrations.AddField(
            model_name="transactionattachment",
            name="transaction",
            field=models.ForeignKey(
                db_column="transaction_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_attachments",
                to="account.transaction",
            ),
        ),
        migrations.AddField(
            model_name="userassignedbusiness",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assigned_businesses",
                to="account.businessaccount",
            ),
        ),
        migrations.AddField(
            model_name="userassignedbusiness",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assigned_businesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="organization_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="The default organization currency for the user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_preferences",
                to="account.organizationcurrency",
                verbose_name="Default Currency",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with these preferences.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_preference",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="account.businessaccount",
            ),
        ),
        migrations.AddField(
            model_name="webhookcall",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_calls",
                to="account.transaction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adminuserrole",
            unique_together={("user", "role")},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email", "organization_id"), name="unique_email_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("phone_number", "organization_id"),
                name="unique_phone_number_organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userassignedbusiness",
            unique_together={("user", "business")},
        ),
    ]
