# Generated by Django 5.1.4 on 2025-07-01 05:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="iban_code",
            field=models.CharField(
                blank=True,
                help_text="The IBAN number for international and local transactions.",
                max_length=34,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="commercial_registration_number",
            field=models.CharField(
                blank=True,
                help_text="The Commercial Registration number for the business.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="vat_account_number",
            field=models.CharField(
                blank=True,
                help_text="The VAT account number for the business.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_number",
            field=models.CharField(
                blank=True,
                help_text="The user's personal identification number.",
                max_length=50,
                null=True,
            ),
        ),
    ]
