# Generated by Django 5.1.4 on 2025-07-01 09:38

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_bankaccount_iban_code_and_more"),
        ("jeweler", "0005_remove_jewelryproduction_platform_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="jewelry_production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="jeweler.jewelryproduction",
            ),
        ),
    ]
