# Generated by Django 5.1.4 on 2025-07-03 12:31

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_transaction_jewelry_production"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="The amount after the transaction was created.",
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="previous_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="The amount before the transaction was created.",
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
