# Generated by Django 5.1.4 on 2025-07-09 12:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_transaction_current_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("mm_yy", models.CharField(max_length=5)),
                ("transaction_code", models.CharField(max_length=10)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Receipt Sequence",
                "verbose_name_plural": "Receipt Sequences",
                "db_table": "receipt_sequences",
                "ordering": ["-created_at"],
                "unique_together": {("mm_yy", "transaction_code")},
            },
        ),
    ]
