# Generated by Django 5.1.4 on 2025-07-16 12:18

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_receiptsequence"),
        ("investor", "0006_assetcontribution_pool_contributor"),
        ("jeweler", "0009_alter_musharakahcontractrenewal_musharakah_contract_request"),
        ("sooq_althahab_admin", "0007_alter_poolcontribution_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gt", 0),
                    ("business_subscription__isnull", False),
                    _connector="OR",
                ),
                name="amount_zero_requires_subscription",
            ),
        ),
    ]
