# Generated by Django 5.1.4 on 2025-07-17 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
