# Generated by Django 5.1.4 on 2025-07-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_address_options"),
        (
            "sooq_althahab_admin",
            "0009_pool_equity_max_pool_equity_min_pool_penalty_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRiskLevel",
            fields=[
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="HIGH",
                        help_text="Risk classification such as Low, Medium, or High.",
                        max_length=10,
                    ),
                ),
                (
                    "equity_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum equity percentage for this risk level.",
                        max_digits=5,
                    ),
                ),
                (
                    "equity_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Maximum equity percentage for this risk level.",
                        max_digits=5,
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Penalty amount associated with this risk level.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allowed_durations",
                    models.ManyToManyField(
                        help_text="Which durations are allowed for this risk level.",
                        related_name="risk_levels",
                        to="sooq_althahab_admin.musharakahdurationchoices",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Level",
                "verbose_name_plural": "Risk Levels",
                "db_table": "risk_levels",
                "ordering": ["risk_level"],
            },
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="risk_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Risk level assigned to the business. Required for jewelers/designers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="account.organizationrisklevel",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrisklevel",
            constraint=models.UniqueConstraint(
                fields=("organization_id", "risk_level"), name="unique_org_risk_level"
            ),
        ),
    ]
