# Generated by Django 5.1.4 on 2025-07-22 04:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_alter_organizationrisklevel_equity_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationrisklevel",
            name="equity_max",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Maximum equity percentage for this risk level.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="organizationrisklevel",
            name="equity_min",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Minimum equity percentage for this risk level.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="organizationrisklevel",
            name="penalty_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Penalty amount associated with this risk level.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="organizationrisklevel",
            name="risk_level",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="HIGH",
                help_text="Risk classification such as Low, Medium, or High.",
                max_length=10,
            ),
        ),
    ]
