# Generated by Django 5.1.4 on 2025-07-22 11:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_organizationrisklevel_equity_max_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_organization",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_phone_number_organization",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_verified", True), ("phone_verified", True)),
                fields=("email", "organization_id"),
                name="unique_email_verified_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_verified", True), ("phone_verified", True)),
                fields=("phone_number", "organization_id"),
                name="unique_phone_verified_organization",
            ),
        ),
    ]
