# Generated by Django 5.1.4 on 2025-07-23 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_remove_user_unique_email_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="individual_aml_verified",
        ),
    ]
