# Generated by Django 5.1.4 on 2025-07-24 10:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_remove_user_individual_aml_verified"),
        ("sooq_althahab_admin", "0013_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationrisklevel",
            name="unique_org_risk_level",
        ),
        migrations.AddConstraint(
            model_name="organizationrisklevel",
            constraint=models.UniqueConstraint(
                fields=("organization_id", "risk_level"),
                name="unique_org_risk_level_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrisklevel",
            constraint=models.UniqueConstraint(
                fields=("organization_id", "equity_min"), name="unique_org_equity_min"
            ),
        ),
    ]
