# Generated by Django 5.1.4 on 2025-07-31 07:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_remove_organizationrisklevel_unique_org_risk_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="nationality",
            field=models.CharField(max_length=32),
        ),
    ]
