# Generated by Django 5.1.4 on 2025-08-13 10:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_alter_address_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="log_details",
            field=models.TextField(
                blank=True,
                help_text="Detailed log information from the payment gateway.",
                null=True,
            ),
        ),
    ]
