# Generated by Django 5.1.4 on 2025-08-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_transaction_log_details'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_verified_organization',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_phone_verified_organization',
        ),
    ]
