# Generated by Django 5.1.4 on 2025-08-26 10:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_remove_user_unique_email_verified_organization_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="businessaccountdocument",
            constraint=models.UniqueConstraint(
                fields=("business", "doc_type"), name="unique_business_document_type"
            ),
        ),
    ]
