# Generated by Django 5.1.4 on 2025-08-27 10:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0019_businessaccountdocument_unique_business_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="declined_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided for declining document verification reason.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="event",
            field=models.CharField(
                blank=True,
                help_text="The URL to the Shufti Pro event.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reference_id",
            field=models.CharField(
                blank=True,
                help_text="The reference ID provided by Shufti Pro for this verification request.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_url",
            field=models.CharField(
                blank=True,
                help_text="The URL to the Shufti Pro verification session.",
                max_length=500,
                null=True,
            ),
        ),
    ]
