# Generated by Django 5.1.4 on 2025-09-01 05:56

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0020_user_declined_reason_user_event_user_reference_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSupportRequestAttachments",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attachment", models.CharField(max_length=255)),
                (
                    "contact_support",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_support_attachments",
                        to="account.contactsupportrequest",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Support Request Attachment",
                "verbose_name_plural": "Contact Support Request Attachments",
                "db_table": "contact_support_request_attachments",
            },
        ),
    ]
