# Generated by Django 5.1.4 on 2025-10-10 11:34

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0022_organizationrisklevel_max_musharakah_weight"),
        ("jeweler", "0032_musharakahcontractrequest_impacted_party_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessaccount",
            name="remark",
            field=models.TextField(
                blank=True,
                help_text="Reason or remarks for suspending the business account.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="musharakah_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="jeweler.musharakahcontractrequest",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="musharakah_contract_termination_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "INVESTOR_LOGISTIC_FEE_PAYMENT_TRANSACTION",
                        "Investor Logistic Fee Payment Transaction",
                    ),
                    (
                        "INVESTOR_REFINING_COST_PAYMENT_TRANSACTION",
                        "Investor Refining Cost Payment Transaction",
                    ),
                    (
                        "INVESTOR_EARLY_TERMINATION_PAYMENT_TRANSACTION",
                        "Investor Early Termination Payment Transaction",
                    ),
                    (
                        "JEWELER_SETTLEMENT_PAYMENT_TRANSACTION",
                        "Jeweler Settlement Payment Transaction",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
