# Generated by Django 5.1.4 on 2025-10-11 05:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0023_businessaccount_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp indicating when the payment was successfully completed.",
                null=True,
            ),
        ),
    ]
