# Generated by Django 5.1.4 on 2025-11-20 10:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0025_alter_organizationrisklevel_max_musharakah_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset",
            field=models.BooleanField(default=False),
        ),
    ]
