# Generated by Django 5.1.4 on 2025-12-11 09:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0027_organization_arabic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessaccount",
            name="has_received_intro_grace",
            field=models.BooleanField(
                default=False,
                help_text="Tracks if the business already received the one-time grace days.",
            ),
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="intro_grace_consumed_on",
            field=models.DateField(
                blank=True,
                help_text="Date when the one-time grace days were applied.",
                null=True,
            ),
        ),
    ]
