# Generated by Django 5.1.4 on 2025-12-16 04:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0028_businessaccount_has_received_intro_grace_and_more"),
        ("jeweler", "0038_manufacturingtarget_metal_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="profit_distribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="jeweler.jewelryprofitdistribution",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("PAYMENT", "Payment"),
                    ("PROFIT_DISTRIBUTION", "Profit Distribution"),
                ],
                max_length=20,
            ),
        ),
    ]
