# Generated by Django 5.1.4 on 2025-06-25 13:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreciousItemImage",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Precious Item Image",
                "verbose_name_plural": "Precious Item Images",
                "db_table": "precious_item_images",
            },
        ),
        migrations.CreateModel(
            name="PreciousMetal",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=10, max_digits=18)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("condition", models.CharField(blank=True, max_length=50)),
                ("packaging", models.CharField(blank=True, max_length=100, null=True)),
                ("manufacture_date", models.DateTimeField(blank=True, null=True)),
                ("treatment", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Precious Metal",
                "verbose_name_plural": "Precious Metals",
                "db_table": "precious_metals",
            },
        ),
        migrations.CreateModel(
            name="PreciousStone",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cut_grade",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="EXCELLENT",
                        help_text="Select cut quality grade.",
                        max_length=15,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "polish",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="EXCELLENT",
                        help_text="Select the polish quality grade.",
                        max_length=15,
                    ),
                ),
                (
                    "symmetry",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="EXCELLENT",
                        help_text="Select the symmetry quality grade.",
                        max_length=15,
                    ),
                ),
                (
                    "fluorescence",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("FAINT", "Faint"),
                            ("MEDIUM", "Medium"),
                            ("STRONG", "Strong"),
                            ("VERY_STRONG", "Very Strong"),
                        ],
                        default="NONE",
                        help_text="Select the fluorescence quality grade.",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Precious Stone",
                "verbose_name_plural": "Precious Stones",
                "db_table": "precious_stones",
            },
        ),
        migrations.CreateModel(
            name="PreciousItem",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[("metal", "Metal"), ("stone", "Stone")], max_length=20
                    ),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "premium_value_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("AMOUNT", "Amount"),
                            ("BOTH", "Both"),
                        ],
                        default="PERCENTAGE",
                        help_text="Select whether the premium is entered as a percentage or a fixed amount.",
                        max_length=10,
                    ),
                ),
                (
                    "premium_price_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Premium price rate as a decimal (e.g., 0.05 for 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "premium_price_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "additional_features",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("GIA", "GIA"),
                            ("IGI", "IGI"),
                            ("NOT_CERTIFIED", "Not Certified"),
                        ],
                        default="NOT_CERTIFIED",
                        help_text="Select the certificate type.",
                        max_length=15,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "report_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "date_of_issue",
                    models.DateField(
                        blank=True,
                        help_text="The date when the certificate was issued.",
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "clarity",
                    models.CharField(
                        choices=[
                            ("FL", "Flawless"),
                            ("IF", "Internally Flawless"),
                            ("VVS1", "Very, Very Slightly Included (VVS1)"),
                            ("VVS2", "Very, Very Slightly Included (VVS2)"),
                            ("VS1", "Very Slightly Included (VS1)"),
                            ("VS2", "Very Slightly Included (VS2)"),
                            ("SI1", "Slightly Included (SI1)"),
                            ("SI2", "Slightly Included (SI2)"),
                            ("I1", "Included (I1) - Visible Flaws"),
                            ("I3", "Included (I3) - Visible Flaws"),
                        ],
                        default="FL",
                        help_text="Select clarity grade.",
                        max_length=15,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("COLORLESS_BEST", "Colorless-Best"),
                            ("COLORLESS", "Colorless"),
                            ("NEAR_COLORLESS", "Near Colorless"),
                            ("FAINT_YELLOW", "Faint Yellow"),
                            ("NOTICEABLE_COLOR", "Noticeable Color"),
                        ],
                        default="COLORLESS_BEST",
                        help_text="Select the color grade.",
                        max_length=20,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precious_items",
                        to="account.businessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precious Item",
                "verbose_name_plural": "Precious Items",
                "db_table": "precious_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
