# Generated by Django 5.1.4 on 2025-06-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0002_initial"),
        ("seller", "0001_initial"),
        ("sooq_althahab_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preciousitem",
            name="carat_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="precious_items",
                to="sooq_althahab_admin.metalcarattype",
            ),
        ),
        migrations.AddField(
            model_name="preciousitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_preciousitem",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="preciousitem",
            name="material_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precious_items",
                to="sooq_althahab_admin.materialitem",
            ),
        ),
        migrations.AddField(
            model_name="preciousitem",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="account.organization",
            ),
        ),
        migrations.AddField(
            model_name="preciousitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_by_preciousitem",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="preciousitemimage",
            name="precious_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="seller.preciousitem",
            ),
        ),
        migrations.AddField(
            model_name="preciousmetal",
            name="precious_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precious_metal",
                to="seller.preciousitem",
            ),
        ),
        migrations.AddField(
            model_name="preciousstone",
            name="precious_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precious_stone",
                to="seller.preciousitem",
            ),
        ),
        migrations.AddField(
            model_name="preciousstone",
            name="shape_cut",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="precious_stones",
                to="sooq_althahab_admin.stonecutshape",
            ),
        ),
        migrations.AddConstraint(
            model_name="preciousitem",
            constraint=models.UniqueConstraint(
                fields=("report_number", "organization_id"),
                name="unique_report_number_organization",
            ),
        ),
    ]
