# Generated by Django 5.1.4 on 2025-08-13 10:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preciousitem",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("GIA", "GIA"),
                    ("IGI", "IGI"),
                    ("DANAT", "Danat"),
                    ("NOT_CERTIFIED", "Not Certified"),
                ],
                default="NOT_CERTIFIED",
                help_text="Select the certificate type.",
                max_length=15,
            ),
        ),
    ]
