# Generated by Django 5.1.4 on 2025-08-21 06:29

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0003_alter_preciousitem_certificate_type"),
        ("sooq_althahab_admin", "0015_alter_subscriptionplan_commission_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preciousitem",
            name="color",
        ),
        migrations.AddField(
            model_name="preciousstone",
            name="color",
            field=models.ForeignKey(
                blank=True,
                help_text="Only for diamonds",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="precious_stone",
                to="sooq_althahab_admin.jewelryproductcolor",
            ),
        ),
    ]
