# Generated by Django 5.1.4 on 2025-09-01 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0005_remove_preciousitem_clarity_preciousstone_clarity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preciousstone",
            name="clarity",
        ),
    ]
