# Generated by Django 5.1.4 on 2025-09-01 09:30

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0006_remove_preciousstone_clarity"),
        ("sooq_althahab_admin", "0018_stoneclarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="preciousstone",
            name="clarity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="precious_stone",
                to="sooq_althahab_admin.stoneclarity",
            ),
        ),
    ]
