# Generated by Django 5.1.4 on 2025-09-16 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0007_preciousstone_clarity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preciousitem",
            name="serial_number",
        ),
    ]
