from django.db.models import TextChoices


class NotificationTypes(TextChoices):
    """Enum for specifying different types of notifications."""

    # Purchase requests notifications
    PURCHASE_REQUEST_CREATED = "PURCHASE_REQUEST_CREATED"
    PURCHASE_REQUEST_APPROVED = "PURCHASE_REQUEST_APPROVED"
    PURCHASE_REQUEST_REJECTED = "PURCHASE_REQUEST_REJECTED"
    PURCHASE_REQUEST_COMPLETED = "PURCHASE_REQUEST_COMPLETED"

    # Sale requests notifications
    SALE_REQUEST_CREATED = "SALE_REQUEST_CREATED"
    SALE_REQUEST_APPROVED = "SALE_REQUEST_APPROVED"
    SALE_REQUEST_REJECTED = "SALE_REQUEST_REJECTED"
    SALE_REQUEST_COMPLETED = "SALE_REQUEST_COMPLETED"

    # Purchase requests payment notifications
    PURCHASE_REQUEST_PAYMENT_TRANSFER = "PURCHASE_REQUEST_PAYMENT_TRANSFER"
    PURCHASE_REQUEST_PAYMENT_RECEIVED = "PURCHASE_REQUEST_PAYMENT_RECEIVED"
    PURCHASE_REQUEST_PAYMENT_FAILED = "PURCHASE_REQUEST_PAYMENT_FAILED"

    # Withdraw/Deposit request notifications
    WITHDRAW_REQUEST_APPROVED = "WITHDRAW_REQUEST_APPROVED"
    WITHDRAW_REQUEST_REJECTED = "WITHDRAW_REQUEST_REJECTED"
    WITHDRAW_REQUEST_CREATED = "WITHDRAW_REQUEST_CREATED"
    DEPOSIT_REQUEST_APPROVED = "DEPOSIT_REQUEST_APPROVED"
    DEPOSIT_REQUEST_REJECTED = "DEPOSIT_REQUEST_REJECTED"
    DEPOSIT_REQUEST_CREATED = "DEPOSIT_REQUEST_CREATED"

    # Musharakah contract request notifications
    MUSHARAKAH_CONTRACT_TERMINATION_REQUEST = "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST"
    MUSHARAKAH_CONTRACT_REQUEST_CREATED = "MUSHARAKAH_CONTRACT_REQUEST_CREATED"
    MUSHARAKAH_CONTRACT_RENEWAL = "MUSHARAKAH_CONTRACT_RENEWAL"
    MUSHARAKAH_CONTRACT_TERMINATED = "MUSHARAKAH_CONTRACT_TERMINATED"
    MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_APPROVED = (
        "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_APPROVED"
    )
    MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_REJECTED = (
        "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_REJECTED"
    )
    MUSHARAKAH_CONTRACT_REQUEST_APPROVED = "MUSHARAKAH_CONTRACT_REQUEST_APPROVED"
    MUSHARAKAH_CONTRACT_REQUEST_REJECTED = "MUSHARAKAH_CONTRACT_REQUEST_REJECTED"
    MUSHARAKAH_CONTRACT_REQUESTS_CLOSED = "MUSHARAKAH_CONTRACT_REQUESTS_CLOSED"
    MUSHARAKAH_CONTRACT_TERMINATION_PAYMENT = "MUSHARAKAH_CONTRACT_TERMINATION_PAYMENT"
    MUSHARAKAH_CONTRACT_TERMINATION_PAYMENT_REQUEST = (
        "MUSHARAKAH_CONTRACT_TERMINATION_PAYMENT_REQUEST"
    )

    # Asset contribution in Pools/Musharakah contract request notifications
    ASSET_CONTRIBUTED_IN_POOL = "ASSET_CONTRIBUTED_IN_POOL"
    ASSET_CONTRIBUTED_IN_MUSHARAKAH_CONTRACT_REQUEST = (
        "ASSET_CONTRIBUTED_IN_MUSHARAKAH_CONTRACT_REQUEST"
    )
    POOL_CONTRIBUTION_APPROVED = "POOL_CONTRIBUTION_APPROVED"
    POOL_CONTRIBUTION_REJECTED = "POOL_CONTRIBUTION_REJECTED"
    POOL_CLOSED_DATE_UPDATED = "POOL_CLOSED_DATE_UPDATED"
    POOL_OPPORTUNITY_AVAILABLE = "POOL_OPPORTUNITY_AVAILABLE"

    # No investor notifications in musharakah contract request to admin
    NO_INVESTOR_ASSIGNED_TO_MUSHARAKAH_CONTRACT_REQUEST = (
        "NO_INVESTOR_ASSIGNED_TO_MUSHARAKAH_CONTRACT_REQUEST"
    )

    # Manufacturing Request notifications
    MANUFACTURING_REQUEST_CREATED = "MANUFACTURING_REQUEST_CREATED"
    MANUFACTURING_ESTIMATION_REQUEST = "MANUFACTURING_ESTIMATION_REQUEST"
    MANUFACTURING_ESTIMATION_REQUEST_ACCEPTED = (
        "MANUFACTURING_ESTIMATION_REQUEST_ACCEPTED"
    )
    MANUFACTURING_ESTIMATION_REQUEST_REJECTED = (
        "MANUFACTURING_ESTIMATION_REQUEST_REJECTED"
    )
    JEWELRY_PRODUCTION_STATUS_UPDATED = "JEWELRY_PRODUCTION_STATUS_UPDATED"
    JEWELRY_PRODUCTION_CORRECTION_AMOUNT_ADDED = (
        "JEWELRY_PRODUCTION_CORRECTION_AMOUNT_ADDED"
    )
    JEWELRY_PRODUCTION_STONE_AMOUNT_ADDED = "JEWELRY_PRODUCTION_STONE_AMOUNT_ADDED"

    JEWELRY_PRODUCT_INSPECTION_STATUS_UPDATED = (
        "JEWELRY_PRODUCT_INSPECTION_STATUS_UPDATED"
    )

    MANUFACTURING_REQUEST_PAYMENT = "MANUFACTURING_REQUEST_PAYMENT"
    JEWELRY_PRODUCT_INSPECTION = "JEWELRY_PRODUCT_INSPECTION"
    JEWELRY_PRODUCTION_PAYMENT = "JEWELRY_PRODUCTION_PAYMENT"
    JEWELRY_PRODUCTION_DELIVERY_STATUS = "JEWELRY_PRODUCTION_DELIVERY_STATUS"

    # Business Subscription Plan notifications
    BUSINESS_SUBSCRIPTION_PLAN = "BUSINESS_SUBSCRIPTION_PLAN"
    BUSINESS_SUBSCRIPTION_EXPIRING_SOON = (
        "BUSINESS_SUBSCRIPTION_EXPIRING_SOON",
        "Business Subscription Expiring Soon",
    )
    BUSINESS_SUBSCRIPTION_EXPIRED = (
        "BUSINESS_SUBSCRIPTION_EXPIRED",
        "Business Subscription Expired",
    )
    BUSINESS_SUBSCRIPTION_EXPIRING_IN_7_DAYS = (
        "BUSINESS_SUBSCRIPTION_EXPIRING_IN_7_DAYS",
        "Business Subscription Expiring in 7 Days",
    )
    BUSINESS_SUBSCRIPTION_EXPIRING_IN_3_DAYS = (
        "BUSINESS_SUBSCRIPTION_EXPIRING_IN_3_DAYS",
        "Business Subscription Expiring in 3 Days",
    )
    BUSINESS_SUBSCRIPTION_EXPIRING_TODAY = (
        "BUSINESS_SUBSCRIPTION_EXPIRING_TODAY",
        "Business Subscription Expiring Today",
    )
    BUSINESS_SUBSCRIPTION_GRACE_PERIOD_STARTED = (
        "BUSINESS_SUBSCRIPTION_GRACE_PERIOD_STARTED",
        "Business Subscription Grace Period Started",
    )
    BUSINESS_SUBSCRIPTION_SUSPENDED = (
        "BUSINESS_SUBSCRIPTION_SUSPENDED",
        "Business Subscription Suspended",
    )

    # User Update
    USER_UPDATED = "USER_UPDATED"

    # Sold Jewelry Profit Distribution
    SOLD_JEWELRY_PROFIT_DISTRIBUTION = "SOLD_JEWELRY_PROFIT_DISTRIBUTION"


class TransactionRequest(TextChoices):
    APPROVED = "APPROVED", "Approved"
    REJECTED = "REJECTED", "Rejected"


class BusinessAccountSuspensionStatus(TextChoices):
    SUSPEND = "SUSPEND", "Suspend"
    REACTIVATE = "REACTIVATE", "Reactivate"


class PoolStatus(TextChoices):
    OPEN = "OPEN", "Open"
    CLOSED = "CLOSED", "Closed"
    SETTLED = "SETTLED", "Settled"


class Status(TextChoices):
    PENDING = "PENDING", "PENDING"
    APPROVED = "APPROVED", "APPROVED"
    REJECTED = "REJECTED", "REJECTED"


class SubscriptionStatus(TextChoices):
    ACTIVE = "ACTIVE", "ACTIVE"
    PENDING = "PENDING", "PENDING"
    CANCELLED = "CANCELLED", "CANCELLED"


class SubscriptionPaymentAmountVariabilityChoices(TextChoices):
    FIXED = "FIXED", "FIXED"
    VARIABLE = "VARIABLE", "VARIABLE"


class SubscriptionPaymentIntervalChoices(TextChoices):
    MONTHLY = "MONTHLY", "MONTHLY"
    QUARTERLY = "QUARTERLY", "QUARTERLY"
    YEARLY = "YEARLY", "YEARLY"


class SubscriptionPaymentTypeChoices(TextChoices):
    PREPAID = "PREPAID", "PREPAID"
    POSTPAID = "POSTPAID", "POSTPAID"
    FREE_TRIAL = "FREE_TRIAL", "FREE_TRIAL"


class MaterialType(TextChoices):
    METAL = "metal", "Metal"
    STONE = "stone", "Stone"


class StoneOrigin(TextChoices):
    NATURAL = "NATURAL", "Natural"
    LAB_GROWN = "LAB_GROWN", "Lab Grown"


class PaymentStatus(TextChoices):
    PENDING = "PENDING", "PENDING"
    COMPLETED = "COMPLETED", "COMPLETED"
    FAILED = "FAILED", "FAILED"


class FundStatus(TextChoices):
    OPEN = "OPEN", "Open"
    CLOSED = "CLOSED", "Closed"
    SUSPEND = "SUSPEND", "Suspend"
