# Generated by Django 5.1.4 on 2025-06-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase Request"),
                            ("SALE", "Sale Request"),
                        ],
                        default="PURCHASE",
                        help_text="Select whether this is a Purchase Request or Sale Request.",
                        max_length=10,
                    ),
                ),
                (
                    "price_locked",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the purchase request was approved.",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the purchase request was completed.",
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Custom invoice number generated when request is approved.",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("taxes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_cost", models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                "verbose_name": "Purchase Request",
                "verbose_name_plural": "Purchase Requests",
                "db_table": "purchase_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetContribution",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the person making the asset contribution.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[("POOL", "Pool"), ("MUSHARAKAH", "Musharakah")],
                        help_text="Type of contribution (e.g., Pool, Musharakah).",
                        max_length=20,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="The business entity associated with this asset contribution.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_contributions",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Contribution",
                "verbose_name_plural": "Asset Contributions",
                "db_table": "asset_contributions",
                "ordering": ["-created_at"],
            },
        ),
    ]
