# Generated by Django 5.1.4 on 2025-06-25 13:28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("investor", "0001_initial"),
        ("jeweler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontribution",
            name="musharakah_contract_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the Musharakah contract request for this asset contribution.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_contributions",
                to="jeweler.musharakahcontractrequest",
            ),
        ),
    ]
