# Generated by Django 5.1.4 on 2025-06-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0002_initial"),
        ("investor", "0002_initial"),
        ("seller", "0001_initial"),
        ("sooq_althahab_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontribution",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the pool for this asset contribution.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_contributions",
                to="sooq_althahab_admin.pool",
            ),
        ),
        migrations.AddField(
            model_name="assetcontribution",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_by_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="action_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved/rejected the request.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="business",
            field=models.ForeignKey(
                help_text="The business entity associated with this purchase request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to="account.businessaccount",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="organization_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="account.organization",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="precious_item",
            field=models.ForeignKey(
                help_text="Reference to the precious item for this purchase request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to="seller.preciousitem",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="related_purchase_request",
            field=models.ForeignKey(
                blank=True,
                help_text="The original purchase request this sale is derived from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_requests",
                to="investor.purchaserequest",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_by_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetcontribution",
            name="purchase_request",
            field=models.ForeignKey(
                help_text="Reference to the purchase request for this asset contribution.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_contributions",
                to="investor.purchaserequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contribution_type", "MUSHARAKAH"),
                        ("musharakah_contract_request__isnull", False),
                    ),
                    models.Q(("contribution_type", "POOL"), ("pool__isnull", False)),
                    _connector="OR",
                ),
                name="check_contribution_type_requires_related_field",
            ),
        ),
    ]
