# Generated by Django 5.1.4 on 2025-07-01 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_transaction_jewelry_production"),
        ("investor", "0003_initial"),
        ("jeweler", "0005_remove_jewelryproduction_platform_fee_and_more"),
        ("sooq_althahab_admin", "0003_alter_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assetcontribution",
            name="check_contribution_type_requires_related_field",
        ),
        migrations.AddField(
            model_name="assetcontribution",
            name="production_payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the Production Payment for this asset contribution.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_contributions",
                to="jeweler.productionpayment",
            ),
        ),
        migrations.AlterField(
            model_name="assetcontribution",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("POOL", "Pool"),
                    ("MUSHARAKAH", "Musharakah"),
                    ("PRODUCTION_PAYMENT", "Production Payment"),
                ],
                help_text="Type of contribution (e.g., Pool, Musharakah).",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="assetcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contribution_type", "MUSHARAKAH"),
                        ("musharakah_contract_request__isnull", False),
                    ),
                    models.Q(("contribution_type", "POOL"), ("pool__isnull", False)),
                    models.Q(
                        ("contribution_type", "PRODUCTION_PAYMENT"),
                        ("production_payment__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="check_contribution_type_requires_related_field",
            ),
        ),
    ]
