# Generated by Django 5.1.4 on 2025-07-08 04:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "investor",
            "0004_remove_assetcontribution_check_contribution_type_requires_related_field_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Current status of the asset contribution.",
                max_length=20,
            ),
        ),
    ]
