# Generated by Django 5.1.4 on 2025-07-10 10:48

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0005_assetcontribution_status"),
        ("sooq_althahab_admin", "0007_alter_poolcontribution_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontribution",
            name="pool_contributor",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the pool for this asset contribution.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_contributions",
                to="sooq_althahab_admin.poolcontribution",
            ),
        ),
    ]
