# Generated by Django 5.1.4 on 2025-07-17 08:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0006_assetcontribution_pool_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontribution",
            name="price_locked",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
    ]
