# Generated by Django 5.1.4 on 2025-09-10 04:38

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0007_assetcontribution_price_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="pro_rata_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Calculated pro rata fee for this purchase request.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="pro_rata_mode",
            field=models.CharField(
                choices=[
                    ("PREPAID", "PREPAID"),
                    ("POSTPAID", "POSTPAID"),
                    ("FREE_TRIAL", "FREE_TRIAL"),
                ],
                default="POSTPAID",
                help_text="Defines if pro rata is charged per purchase (prepaid) or consolidated annually (postpaid).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="pro_rata_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Pro rata rate as a decimal (e.g., 0.05 for 5%).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
    ]
