# Generated by Django 5.1.4 on 2025-09-24 04:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0008_purchaserequest_pro_rata_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="annual_pro_rata_fee",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Calculated annual pro rata fee for this purchase request.",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="order_cost",
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="platform_fee",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="premium",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="pro_rata_fee",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Calculated pro rata fee for this purchase request.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="taxes",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="total_cost",
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="vat",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
