# Generated by Django 5.1.4 on 2025-09-25 04:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0009_purchaserequest_annual_pro_rata_fee_and_more"),
        ("jeweler", "0028_musharakahcontractrequest_max_musharakah_weight"),
        ("seller", "0008_remove_preciousitem_serial_number"),
        ("sooq_althahab_admin", "0022_pool_max_musharakah_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="storage_box_number",
            field=models.CharField(
                blank=True,
                help_text="The storage box number in the admin locker where this item is stored.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PreciousItemUnit",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique serial number assigned when approving the purchase request.",
                        max_length=50,
                    ),
                ),
                (
                    "system_serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="System serial number assigned by admin when complete's the purchase request.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "musharakah_contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Musharakah contract where this unit is allocated (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precious_item_units",
                        to="jeweler.musharakahcontractrequest",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Pool where this unit is allocated (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precious_item_units",
                        to="sooq_althahab_admin.pool",
                    ),
                ),
                (
                    "precious_item",
                    models.ForeignKey(
                        help_text="The type of precious item (e.g., Gold 24k 20g).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precious_item_units",
                        to="seller.preciousitem",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        help_text="The purchase request where this unit was allocated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precious_item_units",
                        to="investor.purchaserequest",
                    ),
                ),
                (
                    "sale_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="The sale request where this unit was sold (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold_units",
                        to="investor.purchaserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precious Item Unit",
                "verbose_name_plural": "Precious Item Units",
                "db_table": "precious_item_units",
                "unique_together": {("purchase_request", "serial_number")},
            },
        ),
    ]
