# Generated by Django 5.1.4 on 2025-10-10 05:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0010_purchaserequest_storage_box_number_preciousitemunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Current status of the asset contribution.",
                max_length=20,
            ),
        ),
    ]
