# Generated by Django 5.1.4 on 2025-10-13 04:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0011_alter_assetcontribution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                help_text="Current status of the asset contribution.",
                max_length=20,
            ),
        ),
    ]
