# Generated by Django 5.1.4 on 2025-11-13 05:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0012_alter_assetcontribution_status"),
        ("jeweler", "0034_jewelryproduction_ownership"),
        ("seller", "0008_remove_preciousitem_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="jewelry_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Jewelry product after musharakah contract terminates.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to="jeweler.jewelryproduct",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="order_cost",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="platform_fee",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="precious_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the precious item for this purchase request.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_requests",
                to="seller.preciousitem",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase Request"),
                    ("SALE", "Sale Request"),
                    ("JEWELRY_DESIGN", "Jewelry Design"),
                ],
                default="PURCHASE",
                help_text="Select whether this is a Purchase Request or Sale Request.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="taxes",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="vat",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
