# Generated by Django 5.1.4 on 2025-11-18 11:44

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0013_purchaserequest_jewelry_product_and_more"),
        ("jeweler", "0034_jewelryproduction_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreciousItemUnitMusharakahHistory",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "contributed_weight",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "musharakah_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musharakah_histories",
                        to="jeweler.musharakahcontractrequest",
                    ),
                ),
                (
                    "precious_item_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musharakah_histories",
                        to="investor.preciousitemunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precious Item Unit Musharakah History",
                "verbose_name_plural": "Precious Item Unit Musharakah Histories",
                "db_table": "precious_item_unit_musharakah_history",
            },
        ),
    ]
