# Generated by Django 5.1.4 on 2025-11-19 12:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0014_preciousitemunitmusharakahhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="deduction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0.0,
                help_text="Deduction amount set by seller for sale requests. Deducted from live price calculation.",
                max_digits=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="initial_order_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Initial order cost for sale requests (live price calculation before deduction).",
                max_digits=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("APPROVED", "Approved"),
                    ("PENDING_SELLER_PRICE", "Pending Seller Price"),
                    ("PENDING_INVESTOR_CONFIRMATION", "Pending Investor Confirmation"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
