# Generated by Django 5.1.4 on 2025-06-25 13:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelryProductAttachment",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("file", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Jewelry Product Attachment",
                "verbose_name_plural": "Jewelry Product Attachments",
                "db_table": "jewelry_product_attachments",
            },
        ),
        migrations.CreateModel(
            name="JewelryProduction",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "production_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("WAITING_TO_SHIPMENT", "Waiting to Shipment"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("JEWELER_APPROVAL", "Jeweler Approval"),
                            ("ADMIN_APPROVAL", "Admin Approval"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_inspected", models.BooleanField(default=False)),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("admin_approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_uploaded_to_marketplace", models.BooleanField(default=False)),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Production",
                "verbose_name_plural": "Jewelry Productions",
                "db_table": "jewelry_productions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProductMaterial",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[("metal", "Metal"), ("stone", "Stone")], max_length=10
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter the quantity for stones only.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "stone_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stone price (in currency) to be entered by the manufacturer for final payment.",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Material",
                "verbose_name_plural": "Jewelry Product Materials",
                "db_table": "jewelry_product_materials",
            },
        ),
        migrations.CreateModel(
            name="ManufacturingPayment",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("FROM_MUSHARAKAH", "From Musharakah"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Manufacturing Payment",
                "verbose_name_plural": "Manufacturing Payments",
                "db_table": "manufacturing_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturingProductRequestedQuantity",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Status of inspection by the inspector (e.g., Pending, Approved, or Rejected).",
                        max_length=20,
                    ),
                ),
                (
                    "production_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        help_text="Indicates the current stage of product manufacturing as updated by the manufacturer (e.g., Pending, In Progress, or Completed).",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturing Product Requested Quantities",
                "verbose_name_plural": "Manufacturing Product Requested Quantities",
                "db_table": "manufacturing_product_requested_quantities",
            },
        ),
        migrations.CreateModel(
            name="ManufacturingRequest",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "manufacturer_type",
                    models.CharField(
                        choices=[
                            ("TENDER", "Tender"),
                            ("DIRECT_MANUFACTURER", "Direct Manufacturer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expected_completion",
                    models.PositiveIntegerField(
                        help_text="Preferred number of days to complete the manufacturing."
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("QUOTATION_SUBMITTED", "Quotation Submitted"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "material_source",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("FROM_MUSHARAKAH", "From Musharakah"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturing Request",
                "verbose_name_plural": "Manufacturing Requests",
                "db_table": "manufacturing_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturingTarget",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Manufacturing Target",
                "verbose_name_plural": "Manufacturing Targets",
                "db_table": "manufacturing_targets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MusharakahContractRenewal",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "custom_expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Used if jeweler picks a specific expiry date.",
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Musharakah Contract Renewal",
                "verbose_name_plural": "Musharakah Contract Renewals",
                "db_table": "musharakah_contract_renewals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MusharakahContractRequest",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "design_type",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("COLLECTION", "Collection")],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                ("target", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "musharakah_equity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Musharakah contribution percentage (1% to 50%)",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "musharakah_contract_status",
                    models.CharField(
                        choices=[
                            ("NOT_ASSIGNED", "Not Assigned"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                            ("RENEW", "Renew"),
                        ],
                        default="NOT_ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "custom_expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Used if jeweler picks a specific expiry date.",
                        null=True,
                    ),
                ),
                (
                    "cash_contribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("profit_ratio", models.DecimalField(decimal_places=2, max_digits=5)),
                ("termination_reason", models.TextField(blank=True, null=True)),
                (
                    "terminated_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JEWELER", "Jeweler"),
                            ("ADMIN", "Admin"),
                            ("INVESTOR", "Investor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Digital signature for the asset contribution.",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Musharakah Contract Request",
                "verbose_name_plural": "Musharakah Contract Requests",
                "db_table": "musharakah_contract_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MusharakahContractRequestAttachment",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Musharakah Contract Request Attachment",
                "verbose_name_plural": "Musharakah Contract Request Attachments",
                "db_table": "musharakah_contract_request_attachments",
            },
        ),
        migrations.CreateModel(
            name="MusharakahContractRequestQuantity",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Musharakah Contract Request Quantities",
                "verbose_name_plural": "Musharakah Contract Request Quantities",
                "db_table": "musharkah_contract_request_quantities",
            },
        ),
        migrations.CreateModel(
            name="MusharakahContractTerminationRequest",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "termination_request_by",
                    models.CharField(
                        choices=[
                            ("JEWELER", "Jeweler"),
                            ("ADMIN", "Admin"),
                            ("INVESTOR", "Investor"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Musharakah Contract Termination Request",
                "verbose_name_plural": "Musharakah Contract Termination Requests",
                "db_table": "musharakah_contract_termination_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryDesign",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "design_type",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("COLLECTION", "Collection")],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated duration (in days) to complete the collection.",
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_designs",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Design",
                "verbose_name_plural": "Jewelry Designs",
                "db_table": "jewelry_designs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProduct",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "premium_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "metal_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_products",
                        to="jeweler.jewelrydesign",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product",
                "verbose_name_plural": "Jewelry Products",
                "db_table": "jewelry_products",
                "ordering": ["-created_at"],
            },
        ),
    ]
