# Generated by Django 5.1.4 on 2025-06-27 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="jewelryproduction",
            old_name="inspected_at",
            new_name="admin_inspected_at",
        ),
        migrations.RemoveField(
            model_name="jewelryproduction",
            name="inspection_status",
        ),
        migrations.RemoveField(
            model_name="jewelryproductmaterial",
            name="stone_price",
        ),
        migrations.RemoveField(
            model_name="manufacturingproductrequestedquantity",
            name="inspection_status",
        ),
        migrations.AddField(
            model_name="jewelryproduction",
            name="admin_inspection_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ADMIN_APPROVAL", "Admin Approval"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduction",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERD", "Delivered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduction",
            name="is_jeweler_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jewelryproduction",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturingproductrequestedquantity",
            name="admin_inspection_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Status of admin inspection by the inspector (e.g., Pending, Approved, or Rejected).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="manufacturingproductrequestedquantity",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturingproductrequestedquantity",
            name="jeweler_inspection_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Status of jewelery inspection by the inspector (e.g., Pending, Approved, or Rejected).",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="JewelryProductStonePrice",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "stone_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stone price (in currency) to be entered by the manufacturer for final payment.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stone_price_products",
                        to="jeweler.jewelryproduct",
                    ),
                ),
                (
                    "jewelry_product_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stone_price_materials",
                        to="jeweler.jewelryproductmaterial",
                    ),
                ),
                (
                    "jewelry_production",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stone_prices",
                        to="jeweler.jewelryproduction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Stone Price",
                "verbose_name_plural": "Jewelry Product Stone Prices",
                "db_table": "jewelry_product_material_price",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "jewelry_production",
                            "jewelry_product",
                            "jewelry_product_material",
                        ),
                        name="unique_jewelry_stone_price_combination",
                    )
                ],
            },
        ),
    ]
