# Generated by Django 5.1.4 on 2025-06-30 06:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0003_rename_inspected_at_jewelryproduction_admin_inspected_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the musharakah contract request was approved.",
                null=True,
            ),
        ),
    ]
