# Generated by Django 5.1.4 on 2025-07-02 05:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0005_remove_jewelryproduction_platform_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryproduction",
            name="is_payment_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jewelryproduction",
            name="production_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
