# Generated by Django 5.1.4 on 2025-07-02 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0006_jewelryproduction_is_payment_completed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelryProductInspectionAttachment",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("JEWELLERY_INSPECTOR", "Jewellery Inspector"),
                        ],
                        help_text="User type who uploaded the attachment (Admin or Jewelry Inspector).",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        blank=True,
                        help_text="Path or URL to the attachment file (image, document, etc.).",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_attachments",
                        to="jeweler.jewelryproduction",
                    ),
                ),
                (
                    "manufacturing_jewelry_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_attachments",
                        to="jeweler.manufacturingproductrequestedquantity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Inspection Attachment",
                "verbose_name_plural": "Jewelry Product Inspection Attachments",
                "db_table": "jewelry_product_inspection_attachments",
            },
        ),
    ]
