# Generated by Django 5.1.4 on 2025-07-02 10:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0007_jewelryproductinspectionattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingproductrequestedquantity",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
