# Generated by Django 5.1.4 on 2025-07-07 12:10

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0008_manufacturingproductrequestedquantity_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musharakahcontractrenewal",
            name="musharakah_contract_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musharakah_contract_renewals",
                to="jeweler.musharakahcontractrequest",
            ),
        ),
    ]
