# Generated by Django 5.1.4 on 2025-07-21 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0009_alter_musharakahcontractrenewal_musharakah_contract_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musharakahcontractrequest",
            name="risk_level",
        ),
    ]
