# Generated by Django 5.1.4 on 2025-07-21 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0010_remove_musharakahcontractrequest_risk_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musharakahcontractrenewal",
            name="custom_expiry_date",
        ),
        migrations.RemoveField(
            model_name="musharakahcontractrequest",
            name="custom_expiry_date",
        ),
    ]
