# Generated by Django 5.1.4 on 2025-07-22 04:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0011_remove_musharakahcontractrenewal_custom_expiry_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musharakahcontractrequest",
            name="profit_ratio",
        ),
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="equity_max",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Maximum equity percentage for this risk level.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="equity_min",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Minimum equity percentage for this risk level.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="penalty_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Penalty amount associated with this risk level.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="risk_level",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="HIGH",
                help_text="Risk classification such as Low, Medium, or High.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="musharakahcontractrequest",
            name="musharakah_equity",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Equity percentage set during Musharakah creation, based on the jeweler/designer's risk level range (min to max).",
                max_digits=10,
            ),
        ),
    ]
