# Generated by Django 5.1.4 on 2025-07-30 05:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0013_alter_musharakahcontractrequest_equity_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelryproduction",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
