# Generated by Django 5.1.4 on 2025-07-31 10:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0014_alter_jewelryproduction_delivery_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musharakahcontractrequest",
            old_name="signature",
            new_name="investor_signature",
        ),
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="jeweler_signature",
            field=models.CharField(
                default="string",
                help_text="Digital signature of jeweler for the musharakah contract with investor.",
                max_length=500,
            ),
        ),
    ]
