# Generated by Django 5.1.4 on 2025-07-31 10:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0015_rename_signature_musharakahcontractrequest_investor_signature_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="musharakahcontractrequest",
            name="jeweler_signature",
            field=models.CharField(
                help_text="Digital signature of jeweler for the musharakah contract with investor.",
                max_length=500,
            ),
        ),
    ]
