# Generated by Django 5.1.4 on 2025-08-01 12:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0016_alter_musharakahcontractrequest_jeweler_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryproduction",
            name="material_delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                help_text="Indicates the delivery status of the materials that are used in the production (e.g., Pending, Out for delivery, or Delivered).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduction",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                help_text="Indicates the delivery status of the completed jewelry products. (e.g., Pending, Out for delivery, or Delivered).",
                max_length=20,
            ),
        ),
    ]
