# Generated by Django 5.1.4 on 2025-08-08 06:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0017_jewelryproduction_material_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingtarget",
            name="quantity",
            field=models.IntegerField(
                blank=True, help_text="Applicable only for stone materials.", null=True
            ),
        ),
    ]
