# Generated by Django 5.1.4 on 2025-08-12 05:32

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0018_manufacturingtarget_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingtarget",
            name="additional_material",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Additional material allocated for production: if the material is metal, enter the extra weight in grams (supports decimals); if stone, enter the extra quantity as a number (can include fractional counts for precision).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="manufacturingtarget",
            name="material_type",
            field=models.CharField(
                choices=[("metal", "Metal"), ("stone", "Stone")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manufacturingrequest",
            name="material_source",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("MUSHARAKAH", "Musharakah"),
                    ("ASSET", "Asset"),
                    ("MUSHARAKAH_AND_ASSET", "Musharakah and Asset"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("MUSHARAKAH", "Musharakah"),
                    ("ASSET", "Asset"),
                    ("MUSHARAKAH_AND_ASSET", "Musharakah and Asset"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
