# Generated by Django 5.1.4 on 2025-08-12 12:44

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0019_manufacturingtarget_additional_material_and_more"),
        ("sooq_althahab_admin", "0014_subscriptionplan_max_design_count_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jewelryproductstoneprice",
            name="unique_jewelry_stone_price_combination",
        ),
        migrations.RemoveField(
            model_name="jewelryproductstoneprice",
            name="jewelry_product",
        ),
        migrations.RemoveField(
            model_name="jewelryproductstoneprice",
            name="jewelry_product_material",
        ),
        migrations.AddField(
            model_name="jewelryproductstoneprice",
            name="material_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="sooq_althahab_admin.materialitem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jewelryproductstoneprice",
            name="shape_cut",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="sooq_althahab_admin.stonecutshape",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproductstoneprice",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
