# Generated by Django 5.1.4 on 2025-08-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0020_remove_jewelryproductstoneprice_unique_jewelry_stone_price_combination_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturingproductrequestedquantity",
            name="reason",
        ),
        migrations.CreateModel(
            name="InspectedRejectedJewelryProduct",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection during the inspection.",
                        null=True,
                    ),
                ),
                (
                    "rejected_by",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("JEWELLERY_INSPECTOR", "Jewellery Inspector"),
                        ],
                        help_text="User type who rejected the product (Jeweler or Jewelry Inspector).",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturing_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejected_inspected_products",
                        to="jeweler.manufacturingproductrequestedquantity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspected & Rejected Jewelry Product",
                "verbose_name_plural": "Inspected & Rejected Jewelry Products",
                "db_table": "inspected_rejected_jewelry_products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionRejectionAttachment",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        blank=True,
                        help_text="Path or URL to the attachment file (image, document, etc.).",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_rejected_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_rejection_attachments",
                        to="jeweler.inspectedrejectedjewelryproduct",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Rejection Attachment",
                "verbose_name_plural": "Inspection Rejection Attachments",
                "db_table": "inspection_rejection_attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
