# Generated by Django 5.1.4 on 2025-08-14 07:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0021_remove_manufacturingproductrequestedquantity_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelryproductstoneprice",
            name="jewelry_production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stone_prices",
                to="jeweler.jewelryproduction",
            ),
        ),
    ]
