# Generated by Django 5.1.4 on 2025-08-18 08:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0022_alter_jewelryproductstoneprice_jewelry_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectedrejectedjewelryproduct",
            name="rejected_by",
            field=models.CharField(
                choices=[
                    ("JEWELER", "Jeweler"),
                    ("JEWELLERY_INSPECTOR", "Jewellery Inspector"),
                ],
                help_text="User type who rejected the product (Jeweler or Jewelry Inspector).",
                max_length=20,
            ),
        ),
    ]
