# Generated by Django 5.1.4 on 2025-08-21 06:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0023_alter_inspectedrejectedjewelryproduct_rejected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryproductmaterial",
            name="clarity",
            field=models.CharField(
                choices=[
                    ("FL", "Flawless"),
                    ("IF", "Internally Flawless"),
                    ("VVS1", "Very, Very Slightly Included (VVS1)"),
                    ("VVS2", "Very, Very Slightly Included (VVS2)"),
                    ("VS1", "Very Slightly Included (VS1)"),
                    ("VS2", "Very Slightly Included (VS2)"),
                    ("SI1", "Slightly Included (SI1)"),
                    ("SI2", "Slightly Included (SI2)"),
                    ("I1", "Included (I1) - Visible Flaws"),
                    ("I3", "Included (I3) - Visible Flaws"),
                ],
                default="FL",
                help_text="Select clarity grade.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="manufacturingtarget",
            name="clarity",
            field=models.CharField(
                choices=[
                    ("FL", "Flawless"),
                    ("IF", "Internally Flawless"),
                    ("VVS1", "Very, Very Slightly Included (VVS1)"),
                    ("VVS2", "Very, Very Slightly Included (VVS2)"),
                    ("VS1", "Very Slightly Included (VS1)"),
                    ("VS2", "Very Slightly Included (VS2)"),
                    ("SI1", "Slightly Included (SI1)"),
                    ("SI2", "Slightly Included (SI2)"),
                    ("I1", "Included (I1) - Visible Flaws"),
                    ("I3", "Included (I3) - Visible Flaws"),
                ],
                default="FL",
                help_text="Select clarity grade.",
                max_length=15,
            ),
        ),
    ]
