# Generated by Django 5.1.4 on 2025-08-21 10:56

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0024_jewelryproductmaterial_clarity_and_more"),
        ("sooq_althahab_admin", "0015_alter_subscriptionplan_commission_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingtarget",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="manufacturing_targets",
                to="sooq_althahab_admin.jewelryproductcolor",
            ),
        ),
    ]
