# Generated by Django 5.1.4 on 2025-09-01 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0025_manufacturingtarget_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewelryproductmaterial",
            name="clarity",
        ),
        migrations.RemoveField(
            model_name="manufacturingtarget",
            name="clarity",
        ),
    ]
