# Generated by Django 5.1.4 on 2025-09-01 09:30

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0026_remove_jewelryproductmaterial_clarity_and_more"),
        ("sooq_althahab_admin", "0018_stoneclarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryproductmaterial",
            name="clarity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jewelry_product_materials",
                to="sooq_althahab_admin.stoneclarity",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingtarget",
            name="clarity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="manufacturing_targets",
                to="sooq_althahab_admin.stoneclarity",
            ),
        ),
    ]
