# Generated by Django 5.1.4 on 2025-09-25 04:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0010_purchaserequest_storage_box_number_preciousitemunit"),
        ("jeweler", "0028_musharakahcontractrequest_max_musharakah_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="storage_box_number",
            field=models.CharField(
                blank=True,
                help_text="The storage box number in the admin locker where this musharakah contract asset is stored.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProductionPaymentAssetAllocation",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "musharakah_contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional Musharakah contract if this unit was linked via Musharakah.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_units",
                        to="jeweler.musharakahcontractrequest",
                    ),
                ),
                (
                    "precious_item_unit",
                    models.ForeignKey(
                        help_text="The serial-numbered precious item unit allocated for this payment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_allocations",
                        to="investor.preciousitemunit",
                    ),
                ),
                (
                    "production_payment",
                    models.ForeignKey(
                        help_text="The serial-numbered precious item unit allocated for this payment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_units",
                        to="jeweler.productionpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Payment Asset Allocation",
                "verbose_name_plural": "Production Payment Asset Allocations",
                "db_table": "production_payment_asset_allocations",
                "ordering": ["-created_at"],
            },
        ),
    ]
