# Generated by Django 5.1.4 on 2025-09-25 12:55

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0029_musharakahcontractrequest_storage_box_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelryproductinspectionattachment",
            name="jewelry_production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_attachments",
                to="jeweler.jewelryproduction",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproductinspectionattachment",
            name="uploaded_by",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("JEWELLERY_INSPECTOR", "Jewellery Inspector"),
                    ("MANUFACTURER", "Manufacturer"),
                ],
                help_text="User type who uploaded the attachment (Admin or Jewelry Inspector).",
                max_length=20,
            ),
        ),
    ]
