# Generated by Django 5.1.4 on 2025-10-10 05:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0030_alter_jewelryproductinspectionattachment_jewelry_production_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingproductrequestedquantity",
            name="admin_inspection_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Status of admin inspection by the inspector (e.g., Pending, Approved, or Rejected).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingproductrequestedquantity",
            name="jeweler_inspection_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Status of jewelery inspection by the inspector (e.g., Pending, Approved, or Rejected).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="musharakahcontractrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="musharakahcontractterminationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
