# Generated by Django 5.1.4 on 2025-10-10 11:34

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jeweler",
            "0031_alter_manufacturingproductrequestedquantity_admin_inspection_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="impacted_party",
            field=models.CharField(
                blank=True,
                choices=[("INVESTOR", "Investor"), ("JEWELER", "Jeweler")],
                help_text="Select the party responsible for termination if the Musharakah Contract is teminated by the admin.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractrequest",
            name="terminated_musharakah_contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the original musharakah contract that was terminated.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_contracts",
                to="jeweler.musharakahcontractrequest",
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="cost_retail_payment_option",
            field=models.CharField(
                blank=True,
                choices=[("PAY_COST", "Pay Cost"), ("PAY_RETAIL", "Pay Retail")],
                help_text="Payment option for the musharakah contract termination: pay cost or pay retail.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="insurance_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="is_investor_early_termination_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="is_investor_logistic_fee_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="is_investor_refining_cost_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="is_jeweler_settlement_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="logistics_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Logistics cost for pay's by the investor when jeweler terminate he musharakah contract.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="logistics_cost_payable_by",
            field=models.CharField(
                blank=True,
                choices=[("JEWELER", "Jeweler"), ("INVESTOR", "Investor")],
                help_text="Indicates who will bear the logistics cost: Jeweler or Investor.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="manufacturing_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Manufacturing cost paid by jeweler.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="refine_sell_payment_option",
            field=models.CharField(
                blank=True,
                choices=[("REFINE", "Refine"), ("SELL", "Sell")],
                help_text="Payment option for the musharakah contract termination: pay refine or sell.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="refining_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Refining cost for asset processing after termination.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="retail_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Retail price paid by investor.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="musharakahcontractterminationrequest",
            name="sell_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Selling cost for asset disposal after termination.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="musharakahcontractrequest",
            name="musharakah_contract_status",
            field=models.CharField(
                choices=[
                    ("NOT_ASSIGNED", "Not Assigned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("TERMINATED", "Terminated"),
                    ("RENEW", "Renew"),
                    ("CLOSED", "Closed"),
                    ("UNDER_TERMINATION", "Under Termination"),
                ],
                default="NOT_ASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="musharakahcontractterminationrequest",
            name="musharakah_contract_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musharakah_contract_termination_requests",
                to="jeweler.musharakahcontractrequest",
            ),
        ),
    ]
