# Generated by Django 5.1.4 on 2025-11-13 05:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0033_alter_musharakahcontractrequest_max_musharakah_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryproduction",
            name="ownership",
            field=models.CharField(
                choices=[("JEWELER", "Jeweler"), ("INVESTOR", "Investor")],
                default="JEWELER",
                help_text="Transfer the ownership of jewelry for the designs.",
                max_length=20,
            ),
        ),
    ]
