# Generated by Django 5.1.4 on 2025-11-18 11:44

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0014_preciousitemunitmusharakahhistory"),
        ("jeweler", "0034_jewelryproduction_ownership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionpaymentassetallocation",
            name="precious_item_unit",
        ),
        migrations.AddField(
            model_name="productionpaymentassetallocation",
            name="precious_item_unit_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="The serial-numbered precious item unit of asset allocated for this payment.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="investor.preciousitemunit",
            ),
        ),
        migrations.AddField(
            model_name="productionpaymentassetallocation",
            name="precious_item_unit_musharakah",
            field=models.ForeignKey(
                blank=True,
                help_text="The serial-numbered precious item unit of musharakah allocated for this payment.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="investor.preciousitemunitmusharakahhistory",
            ),
        ),
    ]
