# Generated by Django 5.1.4 on 2025-12-01 11:36

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0026_user_password_reset"),
        (
            "jeweler",
            "0035_remove_productionpaymentassetallocation_precious_item_unit_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelryProductMarketplace",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "published_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of pieces published to marketplace.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Product description for marketplace listing.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the product is currently active on marketplace.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the product was published to marketplace.",
                    ),
                ),
                (
                    "unpublished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the product was unpublished from marketplace.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_product",
                    models.ForeignKey(
                        help_text="The jewelry product published to marketplace.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_entries",
                        to="jeweler.jewelryproduct",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Marketplace",
                "verbose_name_plural": "Jewelry Product Marketplace",
                "db_table": "jewelry_product_marketplace",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProductMarketplaceImage",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="Path or URL to the image file.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        help_text="The marketplace product this image belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_images",
                        to="jeweler.jewelryproductmarketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Marketplace Image",
                "verbose_name_plural": "Jewelry Product Marketplace Images",
                "db_table": "jewelry_product_marketplace_images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryStock",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "showroom_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity available in showroom.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "marketplace_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity available in marketplace.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "showroom_status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                        ],
                        default="OUT_OF_STOCK",
                        help_text="Stock status for showroom (In Stock or Out of Stock).",
                        max_length=20,
                    ),
                ),
                (
                    "marketplace_status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                        ],
                        default="OUT_OF_STOCK",
                        help_text="Stock status for marketplace (In Stock or Out of Stock).",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("SHOWROOM", "Showroom"),
                            ("MARKETPLACE", "Marketplace"),
                            ("BOTH", "Both"),
                        ],
                        default="SHOWROOM",
                        help_text="Location where the stock is available (Showroom, Marketplace, or Both).",
                        max_length=20,
                    ),
                ),
                (
                    "is_published_to_marketplace",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the product has been published to marketplace.",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_stocks",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_product",
                    models.ForeignKey(
                        help_text="The jewelry product this stock entry belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_stocks",
                        to="jeweler.jewelryproduct",
                    ),
                ),
                (
                    "manufacturing_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The manufacturing product request that created this stock entry.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jewelry_stocks",
                        to="jeweler.manufacturingproductrequestedquantity",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Stock",
                "verbose_name_plural": "Jewelry Stocks",
                "db_table": "jewelry_stocks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jewelryproductmarketplace",
            name="jewelry_stock",
            field=models.ForeignKey(
                blank=True,
                help_text="The stock entry this marketplace publication is based on.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_entries",
                to="jeweler.jewelrystock",
            ),
        ),
        migrations.CreateModel(
            name="JewelryStockRestockRequest",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "requested_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity requested for restocking.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "restock_location",
                    models.CharField(
                        choices=[
                            ("SHOWROOM", "Showroom"),
                            ("MARKETPLACE", "Marketplace"),
                            ("BOTH", "Both"),
                        ],
                        help_text="Location where restocking is needed (Showroom or Marketplace).",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ADMIN_APPROVED", "Admin Approved"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Status of the restock request.",
                        max_length=20,
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the restock was requested.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for the restock request.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_stock",
                    models.ForeignKey(
                        help_text="The stock entry that needs restocking.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_requests",
                        to="jeweler.jewelrystock",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Stock Restock Request",
                "verbose_name_plural": "Jewelry Stock Restock Requests",
                "db_table": "jewelry_stock_restock_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryStockSale",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "sale_location",
                    models.CharField(
                        choices=[
                            ("SHOWROOM", "Showroom"),
                            ("MARKETPLACE", "Marketplace"),
                            ("BOTH", "Both"),
                        ],
                        help_text="Location where the sale occurred (Showroom or Marketplace).",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of pieces sold.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale price for the sold quantity.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(help_text="Date when the sale occurred."),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the customer who purchased.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the customer.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the customer.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the sale.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="NEW",
                        help_text="Current status of the delivery request.",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected or actual delivery date.",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the delivery was completed.",
                        null=True,
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True,
                        help_text="Delivery address of the customer.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_product",
                    models.ForeignKey(
                        help_text="The jewelry product that was sold.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="jeweler.jewelryproduct",
                    ),
                ),
                (
                    "jewelry_stock",
                    models.ForeignKey(
                        help_text="The stock entry this sale is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="jeweler.jewelrystock",
                    ),
                ),
                (
                    "manufacturing_request",
                    models.ForeignKey(
                        help_text="The manufacturing request associated with this sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="jeweler.manufacturingrequest",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Stock Sale",
                "verbose_name_plural": "Jewelry Stock Sales",
                "db_table": "jewelry_stock_sales",
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProfitDistribution",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("JEWELER", "Jeweler"), ("INVESTOR", "Investor")],
                        help_text="Type of recipient (Jeweler or Investor).",
                        max_length=20,
                    ),
                ),
                (
                    "sale_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount for this distribution.",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_of_repurchasing_metal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost of repurchasing the metal/gold used in the jewelry.",
                        max_digits=10,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue after deducting cost of repurchasing metal (sale_amount - cost_of_repurchasing_metal).",
                        max_digits=10,
                    ),
                ),
                (
                    "profit_share_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Profit share percentage for this recipient based on Musharakah equity.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Profit amount for this recipient (revenue * profit_share_percentage / 100).",
                        max_digits=10,
                    ),
                ),
                (
                    "distributed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the profit was distributed.",
                        null=True,
                    ),
                ),
                (
                    "is_distributed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the profit has been distributed.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the profit distribution.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "musharakah_contract",
                    models.ForeignKey(
                        help_text="The Musharakah contract this profit is distributed from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profit_distributions",
                        to="jeweler.musharakahcontractrequest",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "recipient_business",
                    models.ForeignKey(
                        help_text="The business (investor or jeweler) receiving the profit.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profit_distributions_received",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jewelry_sale",
                    models.ForeignKey(
                        help_text="The jewelry sale this profit distribution is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profit_distributions",
                        to="jeweler.jewelrystocksale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Profit Distribution",
                "verbose_name_plural": "Jewelry Profit Distributions",
                "db_table": "jewelry_profit_distributions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="jewelrystock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("jewelry_product", "manufacturing_product"),
                name="unique_jewelry_stock_per_product",
            ),
        ),
    ]
