# Generated by Django 5.1.4 on 2025-12-04 12:12

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0036_jewelryproductmarketplace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewelryprofitdistribution",
            name="is_distributed",
        ),
        migrations.RemoveField(
            model_name="jewelryprofitdistribution",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="jewelryprofitdistribution",
            name="sale_amount",
        ),
        migrations.AddField(
            model_name="manufacturingproductrequestedquantity",
            name="metal_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="jewelryprofitdistribution",
            name="musharakah_contract",
            field=models.ForeignKey(
                blank=True,
                help_text="The Musharakah contract this profit is distributed from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profit_distributions",
                to="jeweler.musharakahcontractrequest",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryprofitdistribution",
            name="revenue",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total revenue generated from this jewelry sale.",
                max_digits=10,
            ),
        ),
    ]
