# Generated by Django 5.1.4 on 2025-12-08 04:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0037_remove_jewelryprofitdistribution_is_distributed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingtarget",
            name="metal_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
