# Generated by Django 5.1.4 on 2026-01-08 09:30

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jeweler", "0038_manufacturingtarget_metal_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musharakahcontractrequest",
            name="design",
        ),
        migrations.AlterField(
            model_name="jewelrydesign",
            name="design_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single"),
                    ("COLLECTION", "Collection"),
                    ("BOTH", "Both"),
                ],
                default="SINGLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="musharakahcontractrequest",
            name="design_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single"),
                    ("COLLECTION", "Collection"),
                    ("BOTH", "Both"),
                ],
                default="SINGLE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MusharakahContractDesign",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musharakah_contract_designs",
                        to="jeweler.jewelrydesign",
                    ),
                ),
                (
                    "musharakah_contract_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musharakah_contract_designs",
                        to="jeweler.musharakahcontractrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Musharakah Contract Design",
                "verbose_name_plural": "Musharakah Contract Designs",
                "db_table": "musharakah_contract_designs",
            },
        ),
    ]
