"""
Django settings for sooq_althahab project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from decimal import Decimal
from pathlib import Path

import firebase_admin
from celery.schedules import crontab
from celery.schedules import schedule

# For dynamic translation we are using gettext_lazy instead of gettext
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from firebase_admin import credentials
from kombu import Queue

from sooq_althahab.sentry import init_sentry

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG"))

# Environment for live metal price
ENVIRONMENT = os.getenv("ENVIRONMENT", "uat")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "django_filters",
    "drf_yasg",
    "rest_framework_simplejwt",
    "storages",
    "corsheaders",
    "django_celery_beat",
    "channels",
]

INHOUSE_APPS = [
    "account",
    "sooq_althahab_admin",
    "jeweler",
    "investor",
    "seller",
    "manufacturer",
]

INSTALLED_APPS = THIRD_PARTY_APPS + DJANGO_APPS + INHOUSE_APPS


AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = ("account.backends.auth.EmailOrganizationBackend",)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sooq_althahab.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "account/"),
            os.path.join(BASE_DIR, "sooq_althahab/templates/"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sooq_althahab.wsgi.application"
ASGI_APPLICATION = "sooq_althahab.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        # Connection pool settings to prevent connection exhaustion
        "CONN_MAX_AGE": 30,  # Close connections after 1 minutes of inactivity
        "OPTIONS": {
            # Connection pool settings
            "connect_timeout": 10,
            # Keep connections alive but limit their lifetime
            "keepalives": 1,
            "keepalives_idle": 30,
            "keepalives_interval": 10,
            "keepalives_count": 5,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Bahrain"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "account.authentication.CustomJWTAuthentication",
    ),
}

if not DEBUG:  # production only
    REST_FRAMEWORK["EXCEPTION_HANDLER"] = "sooq_althahab.utils.custom_exception_handler"

AUTH_USER_MODEL = "account.User"

OTP_EXPIRY_TIME = timedelta(minutes=5)

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 3600
AWS_REGION = os.getenv("AWS_REGION")

DEFAULT_FILE_STORAGE = "storages.backends.s3.S3Storage"
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "UPDATE_LAST_LOGIN": True,
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    },
    "DEFAULT_API_URL": os.getenv("SWAGGER_DEFAULT_API_URL"),
}

# CORS settings for allowed origins
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "0") == "1"

# Additional CORS settings for WebSocket support
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "0") == "1"
CORS_ALLOW_METHODS = os.getenv("CORS_ALLOW_METHODS", "").split(",")
CORS_ALLOW_HEADERS = os.getenv("CORS_ALLOW_HEADERS", "").split(",")

# Email Configurations
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL")

# Organization Email Configuration
ORGANIZATION_BILLING_EMAIL = os.getenv("ORGANIZATION_BILLING_EMAIL")
ORGANIZATION_ACCOUNTS_EMAIL = os.getenv("ORGANIZATION_ACCOUNTS_EMAIL")

LANGUAGES = [("en", _("English")), ("ar", _("Arabic"))]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

# Sentry settings
init_sentry()

# redis configurations
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = os.getenv("REDIS_PORT", 6379)
REDIS_DB = os.getenv("REDIS_DB")


# Set up Channels Redis as the layer backend
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")


# Task Settings
CELERY_TASK_QUEUES = [
    Queue("default"),  # for email, notifications tasks
    Queue("metals_live_price"),  # for fetch_live_metal_prices
]

CELERY_TASK_DEFAULT_QUEUE = "default"

CELERY_TASK_ROUTES = {
    "sooq_althahab.tasks.fetch_live_metal_prices": {"queue": "metals_live_price"},
    "sooq_althahab.tasks.send_mail": {"queue": "default"},
    "sooq_althahab.tasks.send_notification": {"queue": "default"},
    "sooq_althahab.tasks.send_purchase_request_email": {"queue": "default"},
    "sooq_althahab.tasks.send_receipt_to_mail": {"queue": "default"},
    "sooq_althahab.payment_gateway_services.credimax.subscription.tasks.process_subscription_fee_recurring_payment": {
        "queue": "default"
    },
    "sooq_althahab.payment_gateway_services.credimax.subscription.tasks.process_pro_rata_recurring_payment": {
        "queue": "default"
    },
    "sooq_althahab.payment_gateway_services.credimax.subscription.tasks.process_commission_recurring_payment": {
        "queue": "default"
    },
    "sooq_althahab.tasks.close_replacement_musharakah_contract_request": {
        "queue": "default"
    },
    "sooq_althahab.tasks.send_termination_reciept_mail": {"queue": "default"},
}
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_CONTENT_ENCODING = "utf-8"


# Schedule tasks
CELERY_BEAT_SCHEDULE = {
    # Task to fetch live metal prices every 30 seconds
    "fetch_metal_prices": {
        "task": "sooq_althahab.tasks.fetch_live_metal_prices",
        "schedule": schedule(30.0),
        "options": {"queue": "metals_live_price"},
    },
    # Tasks Related to Credimax Payment Gateway
    "check_pending_credimax_transactions": {
        "task": "sooq_althahab.payment_gateway_services.credimax.tasks.check_pending_credimax_transactions",
        "schedule": crontab(minute="*/5"),  # Every 5 minutes
        "options": {"queue": "default"},
    },
    # Subscription Recurring Payment Tasks
    # Task 1: Subscription Fee Recurring Task (Daily) - Handles fixed subscription fees and expired subscriptions
    # "process_subscription_fee_recurring_payment": {
    #     "task": "sooq_althahab.payment_gateway_services.credimax.subscription.tasks.process_subscription_fee_recurring_payment",
    #     "schedule": crontab(hour=2, minute=0),  # Every day at 2:00 AM
    #     "options": {"queue": "default"},
    # },
    # Task 2: Pro Rata Recurring Task (Yearly) - Handles investor pro rata calculations
    # "process_pro_rata_recurring_payment": {
    #     "task": "sooq_althahab.payment_gateway_services.credimax.subscription.tasks.process_pro_rata_recurring_payment",
    #     "schedule": crontab(
    #         day_of_month=1, month_of_year=1, hour=2, minute=0
    #     ),  # January 1st at 2:00 AM
    #     "options": {"queue": "default"},
    # },
    # Task 3: Commission Recurring Task (Yearly) - Handles jeweler commission calculations
    # NOTE: This task is not yet implemented (jewelry sales functionality under development)
    # "process_commission_recurring_payment": {
    #     "task": "sooq_althahab.payment_gateway_services.credimax.subscription.tasks.process_commission_recurring_payment",
    #     "schedule": crontab(day_of_month=1, month_of_year=1, hour=2, minute=0),  # January 1st at 2:00 AM
    #     "options": {"queue": "default"},
    # },
    # Task to manage subscription expiration notifications (notifies users before expiry)
    "manage_subscription_expiration_notifications": {
        "task": "sooq_althahab.tasks.manage_subscription_expiration_notifications",
        "schedule": crontab(minute=0, hour=8),  # Every day at 8:00 AM
        "options": {"queue": "default"},
    },
    # Task Related to Musharakah Contract Requests
    "notify_admin_old_musharakah_requests": {
        "task": "sooq_althahab.tasks.send_notification_to_admin_for_no_investor_in_musharakah_contract_request",
        "schedule": crontab(minute=0, hour=0),  # Every day at 12.00 AM midnight
        "options": {"queue": "default"},
    },
    "close_replacement_musharakah_contract_request": {
        "task": "sooq_althahab.tasks.close_replacement_musharakah_contract_request",
        # "schedule": crontab(minute="*/5"),  # Every 5 minutes (for testing purpose)
        "schedule": crontab(minute=0, hour=8),  # Every day at 8:00 AM
        "options": {"queue": "default"},
    },
    # Task Related to Pools
    "notify_admin_pool": {
        "task": "sooq_althahab.tasks.send_notification_to_admin_for_close_pool",
        "schedule": crontab(minute=0, hour=0),  # Every day at 12.00 AM midnight
        "options": {"queue": "default"},
    },
}
# Gold API configurations
GOLD_API_BASE_URL = os.getenv("GOLD_API_BASE_URL")
GOLD_API_ACCESS_KEY = os.getenv("GOLD_API_ACCESS_KEY")

# Frontend URL for login link
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL")

# Base currency for Gold API
CURRENCY = os.getenv("CURRENCY", "USD")

# The interval for updating the metal prices in the database.
# This value defines the time window (1 hour in this case) for considering price updates.
# It ensures that the prices for metals are updated within 1 hour. After that, a new price record is created.
# This way, we maintain a historical record of metal prices for each hour, allowing us to reference past prices for future analysis.
METAL_PRICE_UPDATE_INTERVAL = timedelta(hours=1)

# Redis Pub/Sub Channel
METAL_PRICE_PUBSUB_CHANNEL_NAME = os.getenv("METAL_PRICE_PUBSUB_CHANNEL_NAME")

# Shufti Pro configurations
SHUFTI_CLIENT_ID = os.getenv("SHUFTI_CLIENT_ID")
SHUFTI_SECRET_KEY = os.getenv("SHUFTI_SECRET_KEY")

S3_FILE_EXPIRATION_DURATION = 3600  # Expiration time for AWS s3 presigned url (seconds)

# Firebase configurations
FIREBASE_APP = (
    os.getenv("FIREBASE_APP", "0") == "1"
)  # This is used enable or disable the Firebase app integration

if FIREBASE_APP:
    credential = {
        # These values are configurable and should be set in the environment for security and flexibility.
        "type": os.getenv("FIREBASE_ACCOUNT_TYPE"),
        "project_id": os.getenv("FIREBASE_PROJECT_ID"),
        "private_key_id": os.getenv("FIREBASE_PRIVATE_KEY_ID"),
        "private_key": os.getenv("FIREBASE_PRIVATE_KEY"),
        "client_email": os.getenv("FIREBASE_CLIENT_EMAIL"),
        "client_id": os.getenv("FIREBASE_CLIENT_ID"),
        "client_x509_cert_url": os.getenv("FIREBASE_CLIENT_X509_CERT_URL"),
        # The following variables are static and do not change.
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "universe_domain": "googleapis.com",
    }

    # Firebase admin (For push notifications).
    firebase_credentials = credentials.Certificate(credential)
    # Initialize the firebase app.
    firebase_admin.initialize_app(firebase_credentials)

SERVICE_FEE_RATE = Decimal(os.getenv("SERVICE_FEE_RATE", "0"))

RSA_PUBLIC_KEY_PEM = os.environ.get("RSA_PUBLIC_KEY_PEM")
RSA_PRIVATE_KEY_PEM = os.environ.get("RSA_PRIVATE_KEY_PEM")

OTP_LENGTH = 6

CONTACT_SUPPORT_EMAIL = os.getenv("CONTACT_SUPPORT_EMAIL")
SUPPORT_CONTACT_NUMBER = os.getenv("SUPPORT_CONTACT_NUMBER")

# -------------------------------
# Credimax Configurations
# -------------------------------

# URLs for 3DS redirect responses and web callbacks
CREDIMAX_3DS_REDIRECT_RESPONSE_URL = os.getenv(
    "CREDIMAX_3DS_REDIRECT_RESPONSE_URL",
    "http://127.0.0.1:8000/api/v1/subscription/3ds-success/",
)
CREDIMAX_3DS_SUCCESS_WEB_CALLBACK_URL = os.getenv(
    "CREDIMAX_3DS_SUCCESS_WEB_CALLBACK_URL",
    "http://192.168.0.106:3000/authenticate-payer?status=success",
)
CREDIMAX_3DS_FAILURE_WEB_CALLBACK_URL = os.getenv(
    "CREDIMAX_3DS_FAILURE_WEB_CALLBACK_URL",
    "http://192.168.0.106:3000/authenticate-payer?status=failure",
)

# Card addition 3DS redirect response URL (backend callback endpoint)
CREDIMAX_CARD_ADDITION_3DS_REDIRECT_RESPONSE_URL = os.getenv(
    "CREDIMAX_CARD_ADDITION_3DS_REDIRECT_RESPONSE_URL",
    "http://127.0.0.1:8000/api/v1/card-addition/3ds-callback/",
)

# Card addition redirect URLs (for mobile app redirect after card addition)
CREDIMAX_CARD_ADDITION_SUCCESS_REDIRECT_URL = os.getenv(
    "CREDIMAX_CARD_ADDITION_SUCCESS_REDIRECT_URL",
    "https://192.168.0.106:3000/add-card-details?status=success",
)
CREDIMAX_CARD_ADDITION_FAILURE_REDIRECT_URL = os.getenv(
    "CREDIMAX_CARD_ADDITION_FAILURE_REDIRECT_URL",
    "https://192.168.0.106:3000/add-card-details?status=failure",
)

# Merchant and API credentials
CREDIMAX_MERCHANT_ID = os.getenv("CREDIMAX_MERCHANT_ID", "")
CREDIMAX_API_USERNAME = f"merchant.{CREDIMAX_MERCHANT_ID}"
CREDIMAX_API_PASSWORD = os.getenv("CREDIMAX_API_PASSWORD", "")

# Other Credimax settings
CREDIMAX_VERSION = os.getenv("CREDIMAX_VERSION", "100")
CREDIMAX_CURRENCY = os.getenv("CREDIMAX_CURRENCY", "BHD")
CREDIMAX_HOSTED_CHECKOUT_PAGE_URL = os.getenv("CREDIMAX_HOSTED_CHECKOUT_PAGE_URL")
CREDIMAX_CHECKOUT_RETURN_URL = os.getenv(
    "CREDIMAX_CHECKOUT_RETURN_URL", "sooq://payment-success"
)
CREDIMAX_CHECKOUT_TIMEOUT_RETURN_URL = os.getenv(
    "CREDIMAX_CHECKOUT_TIMEOUT_RETURN_URL", "sooq://payment-timeout"
)
CREDIMAX_CHECKOUT_TIMEOUT_PERIOD_IN_SECONDS = os.getenv(
    "CREDIMAX_CHECKOUT_TIMEOUT_PERIOD_IN_SECONDS", "600"
)
# Time threshold (in minutes) for stale subscription payment transactions
# Transactions older than this will be checked and marked as failed if still pending
CREDIMAX_STALE_TRANSACTION_TIMEOUT_MINUTES = int(
    os.getenv("CREDIMAX_STALE_TRANSACTION_TIMEOUT_MINUTES", "30")
)
CREDIMAX_HOSTED_CHECKOUT_VERSION = os.getenv(
    "CREDIMAX_HOSTED_CHECKOUT_VERSION", "1.0.0"
)
CREDIMAX_ADDITIONAL_FEE_RATE = os.getenv("CREDIMAX_ADDITIONAL_FEE_RATE", "0")
# Environment-based merchant ID override
PAYMENT_ENV = os.getenv("PAYMENT_ENV")
if PAYMENT_ENV != "prod":
    MERCHANT_ID = f"TEST{CREDIMAX_MERCHANT_ID}"
else:
    MERCHANT_ID = CREDIMAX_MERCHANT_ID

# Base URL for Credimax API
CREDIMAX_BASE_URL = f"https://credimax.gateway.mastercard.com/api/rest/version/{CREDIMAX_VERSION}/merchant/{CREDIMAX_MERCHANT_ID}/"

# -------------------------------
# Benefit Pay Configurations
# -------------------------------

BENEFIT_AES_IV = os.getenv("BENEFIT_AES_IV", "").encode()
BENEFIT_RESOURCE_KEY = os.getenv("BENEFIT_RESOURCE_KEY", "")
BENEFIT_TRANPORTAL_ID = os.getenv("BENEFIT_TRANPORTAL_ID", "")
BENEFIT_TRANPORTAL_PASSWORD = os.getenv("BENEFIT_TRANPORTAL_PASSWORD", "")

BENEFIT_PAYMENT_URL = os.getenv("BENEFIT_PAYMENT_URL", "")
BENEFIT_SUCCESS_URL = os.getenv("BENEFIT_SUCCESS_URL", "")
BENEFIT_FAILURE_URL = os.getenv("BENEFIT_FAILURE_URL", "")
BENEFIT_RETURN_URL = os.getenv("BENEFIT_RETURN_URL", "")
BENEFIT_NOTIFICATION_URL = os.getenv("BENEFIT_NOTIFICATION_URL", "")

BENEFIT_ADDITIONAL_FEE_RATE = os.getenv("BENEFIT_ADDITIONAL_FEE_RATE", "0")

# Benefit Pay Deep Link URLs for mobile app
BENEFIT_SUCCESS_RETURN_URL = os.getenv(
    "BENEFIT_SUCCESS_RETURN_URL", "sooq://payment-success"
)
BENEFIT_FAILURE_RETURN_URL = os.getenv(
    "BENEFIT_FAILURE_RETURN_URL", "sooq://payment-failure"
)
BENEFIT_ERROR_RETURN_URL = os.getenv(
    "BENEFIT_ERROR_RETURN_URL", "sooq://payment-failure"
)

# AWS S3 presigned URL expiration time for File PUT operation in seconds.
S3_PRESIGNED_PUT_URL_EXPIRATION_DURATION = os.getenv(
    "S3_PRESIGNED_PUT_URL_EXPIRATION_DURATION", 120
)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


dummy_phone_numbers = os.getenv("DUMMY_PHONE_NUMBERS", "")
DUMMY_PHONE_NUMBERS = dummy_phone_numbers.split(",") if dummy_phone_numbers else []

DEFAULT_SELLER_IDS = os.getenv("DEFAULT_SELLER_IDS", "")
DEFAULT_SELLER_IDS = [i.strip() for i in DEFAULT_SELLER_IDS.split(",") if i.strip()]
