# Generated by Django 5.1.4 on 2025-06-25 13:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import account.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("jeweler", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMetal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "Global Metal",
                "verbose_name_plural": "Global Metals",
                "db_table": "global_metals",
            },
        ),
        migrations.CreateModel(
            name="BillingDetails",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "commission_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT rate as a decimal (e.g., 0.05 for 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="TAX rate as a decimal (e.g., 0.05 for 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final total payable amount for this billing.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="billing_details",
                        to="account.businessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Detail",
                "verbose_name_plural": "Billing Details",
                "db_table": "billing_details",
                "ordering": ["-period_start_date"],
            },
            bases=(models.Model, account.mixins.ReceiptNumberMixin),
        ),
        migrations.CreateModel(
            name="BusinessSavedCardToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("token", models.CharField(max_length=16, unique=True)),
                ("number", models.CharField(max_length=16)),
                ("expiry_month", models.CharField(max_length=2)),
                ("expiry_year", models.CharField(max_length=2)),
                ("card_type", models.CharField(max_length=20)),
                ("card_brand", models.CharField(max_length=20)),
                ("is_used_for_subscription", models.BooleanField(default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_saved_card_tokens",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Saved Card Token",
                "verbose_name_plural": "Business Saved Card Tokens",
                "db_table": "business_saved_card_tokens",
            },
        ),
        migrations.CreateModel(
            name="BusinessSubscriptionPlan",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("cancelled_date", models.DateField(blank=True, null=True)),
                (
                    "billing_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Day of the month when billing occurs (1-31). For end of month, use 31.",
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateField(
                        blank=True, help_text="Next scheduled billing date", null=True
                    ),
                ),
                (
                    "last_billing_date",
                    models.DateField(
                        blank=True, help_text="Last successful billing date", null=True
                    ),
                ),
                (
                    "billing_cycle_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of billing cycles completed"
                    ),
                ),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "payment_interval",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "MONTHLY"),
                            ("QUARTERLY", "QUARTERLY"),
                            ("YEARLY", "YEARLY"),
                        ],
                        default="MONTHLY",
                        help_text="How the customer actually pays: monthly, or yearly",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pro_rata_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "payment_amount_variability",
                    models.CharField(
                        choices=[("FIXED", "FIXED"), ("VARIABLE", "VARIABLE")],
                        default="FIXED",
                        help_text="Specifies whether the subscription payment amount is fixed or varies over time.",
                        max_length=10,
                    ),
                ),
                (
                    "credimax_3ds_transaction_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIALING", "Trialing"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_auto_renew", models.BooleanField(default=True)),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of days to retry failed payments before suspending",
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum number of payment retry attempts"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of retry attempts for failed payment",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_subscription_plan",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "business_saved_card_token",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_subscription_plan",
                        to="sooq_althahab_admin.businesssavedcardtoken",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Subscription Plan",
                "verbose_name_plural": "Business Subscription Plans",
                "db_table": "business_subscription_plans",
            },
        ),
        migrations.CreateModel(
            name="JewelryProductColor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Color",
                "verbose_name_plural": "Jewelry Product Colors",
                "db_table": "jewelry_product_color",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProductType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Product Type",
                "verbose_name_plural": "Jewelry Product Types",
                "db_table": "jewelry_product_type",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceProduct",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "magento_product_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace",
                        to="jeweler.jewelryproduction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Product",
                "verbose_name_plural": "Marketplace Products",
                "db_table": "marketplace_product",
            },
        ),
        migrations.CreateModel(
            name="JewelrySale",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("sold_quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "revenue_to_jeweler",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="sooq_althahab_admin.marketplaceproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jewelry Sale",
                "verbose_name_plural": "Jewelry Sales",
                "db_table": "jewelry_sales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[("metal", "Metal"), ("stone", "Stone")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "global_metal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="sooq_althahab_admin.globalmetal",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Item",
                "verbose_name_plural": "Material Items",
                "db_table": "material_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetalCaratType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "purity_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Purity of gold in percentage (e.g., 99.9 for 24K)",
                        max_digits=5,
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metal Carat Type",
                "verbose_name_plural": "Metal Carat Types",
                "db_table": "metal_carat_type",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetalPriceHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_on_date", models.DateTimeField()),
                (
                    "global_metal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="sooq_althahab_admin.globalmetal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metal Price History",
                "verbose_name_plural": "Metal Price Histories",
                "db_table": "metal_price_histories",
            },
        ),
        migrations.CreateModel(
            name="MusharakahDurationChoices",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("days", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Musharakah Duration Choice",
                "verbose_name_plural": "Musharakah Duration Choices",
                "db_table": "musharakah_duration_choices",
                "ordering": ["days"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_REQUEST_CREATED", "Purchase Request Created"),
                            ("PURCHASE_REQUEST_APPROVED", "Purchase Request Approved"),
                            ("PURCHASE_REQUEST_REJECTED", "Purchase Request Rejected"),
                            (
                                "PURCHASE_REQUEST_COMPLETED",
                                "Purchase Request Completed",
                            ),
                            ("SALE_REQUEST_CREATED", "Sale Request Created"),
                            ("SALE_REQUEST_APPROVED", "Sale Request Approved"),
                            ("SALE_REQUEST_REJECTED", "Sale Request Rejected"),
                            ("SALE_REQUEST_COMPLETED", "Sale Request Completed"),
                            (
                                "PURCHASE_REQUEST_PAYMENT_TRANSFER",
                                "Purchase Request Payment Transfer",
                            ),
                            (
                                "PURCHASE_REQUEST_PAYMENT_RECEIVED",
                                "Purchase Request Payment Received",
                            ),
                            (
                                "PURCHASE_REQUEST_PAYMENT_FAILED",
                                "Purchase Request Payment Failed",
                            ),
                            ("WITHDRAW_REQUEST_APPROVED", "Withdraw Request Approved"),
                            ("WITHDRAW_REQUEST_REJECTED", "Withdraw Request Rejected"),
                            ("WITHDRAW_REQUEST_CREATED", "Withdraw Request Created"),
                            ("DEPOSIT_REQUEST_APPROVED", "Deposit Request Approved"),
                            ("DEPOSIT_REQUEST_REJECTED", "Deposit Request Rejected"),
                            ("DEPOSIT_REQUEST_CREATED", "Deposit Request Created"),
                            (
                                "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST",
                                "Musharakah Contract Termination Request",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_REQUEST_CREATED",
                                "Musharakah Contract Request Created",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_RENEWAL",
                                "Musharakah Contract Renewal",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_TERMINATED",
                                "Musharakah Contract Terminated",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_APPROVED",
                                "Musharakah Contract Termination Request Approved",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_REJECTED",
                                "Musharakah Contract Termination Request Rejected",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_REQUEST_APPROVED",
                                "Musharakah Contract Request Approved",
                            ),
                            (
                                "MUSHARAKAH_CONTRACT_REQUEST_REJECTED",
                                "Musharakah Contract Request Rejected",
                            ),
                            ("ASSET_CONTRIBUTED_IN_POOL", "Asset Contributed In Pool"),
                            (
                                "ASSET_CONTRIBUTED_IN_MUSHARAKAH_CONTRACT_REQUEST",
                                "Asset Contributed In Musharakah Contract Request",
                            ),
                            (
                                "POOl_CONTRIBUTION_APPROVED",
                                "Pool Contribution Approved",
                            ),
                            (
                                "POOl_CONTRIBUTION_REJECTED",
                                "Pool Contribution Rejected",
                            ),
                            (
                                "NO_INVESTOR_ASSIGNED_TO_MUSHARAKAH_CONTRACT_REQUEST",
                                "No Investor Assigned To Musharakah Contract Request",
                            ),
                            (
                                "MANUFACTURING_ESTIMATION_REQUEST_ACCEPTED",
                                "Manufacturing Estimation Request Accepted",
                            ),
                            (
                                "MANUFACTURING_ESTIMATION_REQUEST_REJECTED",
                                "Manufacturing Estimation Request Rejected",
                            ),
                            (
                                "MANUFACTURING_REQUEST_PAYMENT",
                                "Manufacturing Request Payment",
                            ),
                        ],
                        help_text="Select the notification type",
                        max_length=100,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("object_id", models.CharField(blank=True, max_length=18, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationBankAccount",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="The name of the bank where the account is held.",
                        max_length=255,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="The bank account number", max_length=20
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="The name associated with the bank account.",
                        max_length=255,
                    ),
                ),
                (
                    "iban_code",
                    models.CharField(
                        blank=True,
                        help_text="The IBAN number for international and local transactions.",
                        max_length=34,
                        null=True,
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True,
                        help_text="A unique code used to identify the bank for international transactions.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_bank_accounts",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Bank Account",
                "verbose_name_plural": "Organization Bank Accounts",
                "db_table": "organization_bank_account",
            },
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        choices=[("metal", "Metal"), ("stone", "Stone")],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "target",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("SETTLED", "Settled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "expected_return_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected return percentage for the pool, e.g. 15.25%",
                        max_digits=5,
                    ),
                ),
                (
                    "actual_return_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual return generated after closing",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "return_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Return amount for this contribution after pool closure.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("closes_on", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_pools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "carat_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="sooq_althahab_admin.metalcarattype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pools",
                        to="sooq_althahab_admin.materialitem",
                    ),
                ),
                (
                    "musharakah_contract_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the Musharakah contract request associated with this pool.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="jeweler.musharakahcontractrequest",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pool",
                "verbose_name_plural": "Pools",
                "db_table": "pools",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PoolContribution",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "return_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distributed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_contributions",
                        to="account.businessaccount",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_contributions",
                        to="sooq_althahab_admin.pool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pool Contribution",
                "verbose_name_plural": "Pool Contributions",
                "db_table": "pool_contributions",
            },
        ),
        migrations.CreateModel(
            name="StoneCutShape",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stone Cut Shape",
                "verbose_name_plural": "Stone Cut Shapes",
                "db_table": "stone_cut_shape",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pool",
            name="cut_shape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="sooq_althahab_admin.stonecutshape",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionBillingHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("billing_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_attempt", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_history",
                        to="sooq_althahab_admin.businesssubscriptionplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Billing History",
                "verbose_name_plural": "Subscription Billing Histories",
                "db_table": "subscription_billing_history",
                "ordering": ["-billing_date"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SELLER", "Seller"),
                            ("JEWELER", "Jeweler"),
                            ("INVESTOR", "Investor"),
                            ("MANUFACTURER", "Manufacturer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="BUSINESS",
                        max_length=30,
                    ),
                ),
                ("subscription_code", models.CharField(max_length=12, unique=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=12, help_text="Duration of the subscription in months"
                    ),
                ),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        help_text="How the customer actually billed: monthly, or yearly",
                        max_length=20,
                    ),
                ),
                (
                    "payment_interval",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "MONTHLY"),
                            ("QUARTERLY", "QUARTERLY"),
                            ("YEARLY", "YEARLY"),
                        ],
                        default="MONTHLY",
                        help_text="How the customer actually pays: monthly, or yearly",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount_variability",
                    models.CharField(
                        choices=[("FIXED", "FIXED"), ("VARIABLE", "VARIABLE")],
                        default="FIXED",
                        help_text="Specifies whether the subscription payment amount is fixed or varies over time.",
                        max_length=10,
                    ),
                ),
                (
                    "subscription_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discounted_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pro_rata_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("description", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                        default="PREPAID",
                        help_text="Defines whether the plan is prepaid or postpaid",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_subscription_plan",
                to="sooq_althahab_admin.subscriptionplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesssavedcardtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_used_for_subscription", True)),
                fields=("business",),
                name="unique_active_subscription_token_per_business",
            ),
        ),
        migrations.AddIndex(
            model_name="metalpricehistory",
            index=models.Index(
                fields=["global_metal", "created_at"],
                name="metal_price_global__832bd7_idx",
            ),
        ),
    ]
