# Generated by Django 5.1.4 on 2025-07-09 12:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolcontribution",
            name="signature",
            field=models.CharField(
                blank=True,
                help_text="Digital signature for the asset contribution in pool.",
                max_length=500,
                null=True,
            ),
        ),
    ]
