# Generated by Django 5.1.4 on 2025-07-10 10:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0006_poolcontribution_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poolcontribution",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
