# Generated by Django 5.1.4 on 2025-07-17 08:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0007_alter_poolcontribution_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="payment_type",
            field=models.CharField(
                choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                default="PREPAID",
                help_text="Defines whether the plan is prepaid or postpaid",
                max_length=10,
            ),
        ),
    ]
