# Generated by Django 5.1.4 on 2025-08-11 06:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0013_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_design_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of designs the Jeweler can upload (Free Trial Only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="metal_purchase_max_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum metal weight in grams that the Jeweler can buy from the app (Free Trial Only)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="musharakah_request_max_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum metal weight in grams that the Jeweler can request when joining a Musharakah pool (Free Trial Only)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="businesssubscriptionplan",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("PREPAID", "PREPAID"),
                    ("POSTPAID", "POSTPAID"),
                    ("FREE_TRIAL", "FREE_TRIAL"),
                ],
                default="PREPAID",
                help_text="Defines whether the plan is prepaid or postpaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("PREPAID", "PREPAID"),
                    ("POSTPAID", "POSTPAID"),
                    ("FREE_TRIAL", "FREE_TRIAL"),
                ],
                default="PREPAID",
                help_text="Defines whether the plan is prepaid or postpaid",
                max_length=10,
            ),
        ),
    ]
