# Generated by Django 5.1.4 on 2025-08-22 06:43

from django.db import migrations
from django.db import models


def populate_subscription_snapshot(apps, schema_editor):
    BusinessSubscriptionPlan = apps.get_model(
        "sooq_althahab_admin", "BusinessSubscriptionPlan"
    )
    for bsp in BusinessSubscriptionPlan.objects.filter(subscription_plan__isnull=False):
        if not bsp.subscription_name:
            bsp.subscription_name = bsp.subscription_plan.name
        bsp.save(update_fields=["subscription_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0015_alter_subscriptionplan_commission_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="subscription_name",
            field=models.CharField(
                blank=True,
                help_text="Subscription plan name at the time of purchase",
                max_length=100,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_subscription_snapshot, reverse_code=migrations.RunPython.noop
        ),
    ]
