# Generated by Django 5.1.4 on 2025-09-01 09:29

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_contactsupportrequestattachments"),
        ("sooq_althahab_admin", "0017_alter_notification_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoneClarity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stone Clarity",
                "verbose_name_plural": "Stone Clarities",
                "db_table": "stone_clarity",
                "ordering": ["-created_at"],
            },
        ),
    ]
