# Generated by Django 5.1.4 on 2025-09-10 04:38

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0018_stoneclarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="translated_names",
            field=models.JSONField(
                blank=True,
                help_text="Stores subscription plan name in multiple languages, e.g., {'en': 'Seller Plan', 'ar': 'خطة البائع'}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="businesssubscriptionplan",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Commission rate as a decimal (e.g., 0.05 for 5%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="businesssubscriptionplan",
            name="pro_rata_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Pro rata rate as a decimal (e.g., 0.05 for 5%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Commission rate as a decimal (e.g., 0.05 for 5%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="pro_rata_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Pro rata rate as a decimal (e.g., 0.05 for 5%)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
    ]
