# Generated by Django 5.1.4 on 2025-09-11 12:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0019_subscriptionplan_translated_names_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("IOS", "iOS")], max_length=10
                    ),
                ),
                ("min_required_version", models.CharField(max_length=20)),
                ("app_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
