# Generated by Django 5.1.4 on 2025-09-12 12:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0020_appversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssubscriptionplan",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="business_subscription_plan",
                to="sooq_althahab_admin.subscriptionplan",
            ),
        ),
    ]
