# Generated by Django 5.1.4 on 2025-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sooq_althahab_admin', '0021_alter_businesssubscriptionplan_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='max_musharakah_weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum Musharakah weight for this risk level.', max_digits=5),
        ),
    ]
