# Generated by Django 5.1.4 on 2025-09-26 04:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0022_pool_max_musharakah_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdetails",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Custom invoice number generated when billing is completed.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
