# Generated by Django 5.1.4 on 2025-10-15 06:56

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0024_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="pending_plan_effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the pending plan will take effect (next billing date)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="pending_subscription_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="New subscription plan to be applied at next billing cycle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_business_subscriptions",
                to="sooq_althahab_admin.subscriptionplan",
            ),
        ),
    ]
