# Generated by Django 5.1.4 on 2025-11-03 05:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0026_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="max_musharakah_weight",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Maximum Musharakah weight for this risk level (in grams).",
                max_digits=15,
            ),
        ),
    ]
