# Generated by Django 5.1.4 on 2025-11-12 10:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0027_alter_pool_max_musharakah_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssavedcardtoken",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesssavedcardtoken",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesssavedcardtoken",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
