# Generated by Django 5.1.4 on 2025-11-13 05:37

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0028_businesssavedcardtoken_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pool",
            name="closes_on",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="description",
        ),
        migrations.AddField(
            model_name="materialitem",
            name="stone_origin",
            field=models.CharField(
                choices=[("NATURAL", "Natural"), ("LAB_GROWN", "Lab Grown")],
                db_index=True,
                default="NATURAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="authority_information",
            field=models.CharField(
                blank=True,
                help_text="Domicile or regulatory authority for the pool.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="fund_manager",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="fund_objective",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="URL or path to the pool logo.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="management_fee_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Management Fees rate as a decimal (e.g., 0.15 for 15%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="minimum_investment_grams_per_participant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum investment amount in grams required per participant.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="participation_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total time (in months) allowed for participants to join the pool.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="performance_fee_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Performance Fees rate as a decimal (e.g., 0.15 for 15%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1.0000")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="pool_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total duration of the pool in Years.", null=True
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True,
                help_text="Terms and conditions for participating in the pool.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="poolcontribution",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poolcontribution",
            name="fund_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("SUSPEND", "Suspend"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="materialitem",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="poolcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
