# Generated by Django 5.1.4 on 2025-11-13 11:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sooq_althahab_admin",
            "0029_remove_pool_closes_on_remove_pool_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="terms_and_conditions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
