# Generated by Django 5.1.4 on 2025-11-14 05:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0030_alter_pool_terms_and_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of enabled features for this subscription. Copied from subscription plan at purchase time. Example: ['PURCHASE_ASSETS', 'JOIN_POOLS', 'JOIN_MUSHARAKAH']",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of enabled features for this subscription plan. Example: ['PURCHASE_ASSETS', 'JOIN_POOLS', 'JOIN_MUSHARAKAH']",
                null=True,
            ),
        ),
    ]
