# Generated by Django 5.1.4 on 2025-11-17 06:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0031_businesssubscriptionplan_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscriptionplan",
            name="cancel_at_end_of_billing_cycle",
            field=models.BooleanField(
                default=False,
                help_text="If True, subscription will be cancelled at the end of the current billing cycle (on expiry_date). Admin can set this to discontinue subscription starting from next billing cycle.",
            ),
        ),
    ]
