# Generated by Django 5.1.4 on 2025-12-16 07:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0034_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_REQUEST_CREATED", "Purchase Request Created"),
                    ("PURCHASE_REQUEST_APPROVED", "Purchase Request Approved"),
                    ("PURCHASE_REQUEST_REJECTED", "Purchase Request Rejected"),
                    ("PURCHASE_REQUEST_COMPLETED", "Purchase Request Completed"),
                    ("SALE_REQUEST_CREATED", "Sale Request Created"),
                    ("SALE_REQUEST_APPROVED", "Sale Request Approved"),
                    ("SALE_REQUEST_REJECTED", "Sale Request Rejected"),
                    ("SALE_REQUEST_COMPLETED", "Sale Request Completed"),
                    (
                        "PURCHASE_REQUEST_PAYMENT_TRANSFER",
                        "Purchase Request Payment Transfer",
                    ),
                    (
                        "PURCHASE_REQUEST_PAYMENT_RECEIVED",
                        "Purchase Request Payment Received",
                    ),
                    (
                        "PURCHASE_REQUEST_PAYMENT_FAILED",
                        "Purchase Request Payment Failed",
                    ),
                    ("WITHDRAW_REQUEST_APPROVED", "Withdraw Request Approved"),
                    ("WITHDRAW_REQUEST_REJECTED", "Withdraw Request Rejected"),
                    ("WITHDRAW_REQUEST_CREATED", "Withdraw Request Created"),
                    ("DEPOSIT_REQUEST_APPROVED", "Deposit Request Approved"),
                    ("DEPOSIT_REQUEST_REJECTED", "Deposit Request Rejected"),
                    ("DEPOSIT_REQUEST_CREATED", "Deposit Request Created"),
                    (
                        "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST",
                        "Musharakah Contract Termination Request",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_REQUEST_CREATED",
                        "Musharakah Contract Request Created",
                    ),
                    ("MUSHARAKAH_CONTRACT_RENEWAL", "Musharakah Contract Renewal"),
                    (
                        "MUSHARAKAH_CONTRACT_TERMINATED",
                        "Musharakah Contract Terminated",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_APPROVED",
                        "Musharakah Contract Termination Request Approved",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_TERMINATION_REQUEST_REJECTED",
                        "Musharakah Contract Termination Request Rejected",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_REQUEST_APPROVED",
                        "Musharakah Contract Request Approved",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_REQUEST_REJECTED",
                        "Musharakah Contract Request Rejected",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_REQUESTS_CLOSED",
                        "Musharakah Contract Requests Closed",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_TERMINATION_PAYMENT",
                        "Musharakah Contract Termination Payment",
                    ),
                    (
                        "MUSHARAKAH_CONTRACT_TERMINATION_PAYMENT_REQUEST",
                        "Musharakah Contract Termination Payment Request",
                    ),
                    ("ASSET_CONTRIBUTED_IN_POOL", "Asset Contributed In Pool"),
                    (
                        "ASSET_CONTRIBUTED_IN_MUSHARAKAH_CONTRACT_REQUEST",
                        "Asset Contributed In Musharakah Contract Request",
                    ),
                    ("POOL_CONTRIBUTION_APPROVED", "Pool Contribution Approved"),
                    ("POOL_CONTRIBUTION_REJECTED", "Pool Contribution Rejected"),
                    ("POOL_CLOSED_DATE_UPDATED", "Pool Closed Date Updated"),
                    ("POOL_OPPORTUNITY_AVAILABLE", "Pool Opportunity Available"),
                    (
                        "NO_INVESTOR_ASSIGNED_TO_MUSHARAKAH_CONTRACT_REQUEST",
                        "No Investor Assigned To Musharakah Contract Request",
                    ),
                    ("MANUFACTURING_REQUEST_CREATED", "Manufacturing Request Created"),
                    (
                        "MANUFACTURING_ESTIMATION_REQUEST",
                        "Manufacturing Estimation Request",
                    ),
                    (
                        "MANUFACTURING_ESTIMATION_REQUEST_ACCEPTED",
                        "Manufacturing Estimation Request Accepted",
                    ),
                    (
                        "MANUFACTURING_ESTIMATION_REQUEST_REJECTED",
                        "Manufacturing Estimation Request Rejected",
                    ),
                    (
                        "JEWELRY_PRODUCTION_STATUS_UPDATED",
                        "Jewelry Production Status Updated",
                    ),
                    (
                        "JEWELRY_PRODUCTION_CORRECTION_AMOUNT_ADDED",
                        "Jewelry Production Correction Amount Added",
                    ),
                    (
                        "JEWELRY_PRODUCTION_STONE_AMOUNT_ADDED",
                        "Jewelry Production Stone Amount Added",
                    ),
                    (
                        "JEWELRY_PRODUCT_INSPECTION_STATUS_UPDATED",
                        "Jewelry Product Inspection Status Updated",
                    ),
                    ("MANUFACTURING_REQUEST_PAYMENT", "Manufacturing Request Payment"),
                    ("JEWELRY_PRODUCT_INSPECTION", "Jewelry Product Inspection"),
                    ("JEWELRY_PRODUCTION_PAYMENT", "Jewelry Production Payment"),
                    (
                        "JEWELRY_PRODUCTION_DELIVERY_STATUS",
                        "Jewelry Production Delivery Status",
                    ),
                    ("BUSINESS_SUBSCRIPTION_PLAN", "Business Subscription Plan"),
                    (
                        "BUSINESS_SUBSCRIPTION_EXPIRING_SOON",
                        "Business Subscription Expiring Soon",
                    ),
                    ("BUSINESS_SUBSCRIPTION_EXPIRED", "Business Subscription Expired"),
                    (
                        "BUSINESS_SUBSCRIPTION_EXPIRING_IN_7_DAYS",
                        "Business Subscription Expiring in 7 Days",
                    ),
                    (
                        "BUSINESS_SUBSCRIPTION_EXPIRING_IN_3_DAYS",
                        "Business Subscription Expiring in 3 Days",
                    ),
                    (
                        "BUSINESS_SUBSCRIPTION_EXPIRING_TODAY",
                        "Business Subscription Expiring Today",
                    ),
                    (
                        "BUSINESS_SUBSCRIPTION_GRACE_PERIOD_STARTED",
                        "Business Subscription Grace Period Started",
                    ),
                    (
                        "BUSINESS_SUBSCRIPTION_SUSPENDED",
                        "Business Subscription Suspended",
                    ),
                    ("USER_UPDATED", "User Updated"),
                    (
                        "SOLD_JEWELRY_PROFIT_DISTRIBUTION",
                        "Sold Jewelry Profit Distribution",
                    ),
                ],
                help_text="Select the notification type",
                max_length=100,
            ),
        ),
    ]
