# Generated by Django 5.1.4 on 2025-01-XX XX:XX

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sooq_althahab_admin", "0035_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesssubscriptionplan",
            name="cancel_at_end_of_billing_cycle",
        ),
    ]
