from django.core.management.base import BaseCommand

from account.models import CountryToContinent

COUNTRIES_BY_CONTINENT = {
    "North America": {
        "United States",
        "Canada",
        "Mexico",
        "Guatemala",
        "Belize",
        "Honduras",
        "El Salvador",
        "Nicaragua",
        "Costa Rica",
        "Panama",
        "Bahamas",
        "Cuba",
        "Jamaica",
        "Haiti",
        "Dominican Republic",
        "Barbados",
        "Saint Kitts and Nevis",
        "Antigua and Barbuda",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Grenada",
        "Trinidad and Tobago",
    },
    "South America": {
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",
    },
    "Europe": {
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Netherlands",
        "Belgium",
        "Sweden",
        "Norway",
        "Denmark",
        "Finland",
        "Ireland",
        "Switzerland",
        "Austria",
        "Portugal",
        "Greece",
        "Poland",
        "Czech Republic",
        "Hungary",
        "Romania",
        "Slovakia",
        "Slovenia",
        "Croatia",
        "Bulgaria",
        "Serbia",
        "Bosnia and Herzegovina",
        "Montenegro",
        "Albania",
        "North Macedonia",
        "Lithuania",
        "Latvia",
        "Estonia",
        "Ukraine",
        "Belarus",
        "Russia",
        "Iceland",
        "Moldova",
        "Malta",
        "Liechtenstein",
        "Luxembourg",
        "Monaco",
        "Andorra",
        "San Marino",
        "Vatican City",
    },
    "Africa": {
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cape Verde",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    },
    "Asia": {
        "China",
        "India",
        "Japan",
        "South Korea",
        "North Korea",
        "Indonesia",
        "Pakistan",
        "Bangladesh",
        "Vietnam",
        "Thailand",
        "Philippines",
        "Malaysia",
        "Singapore",
        "Myanmar",
        "Sri Lanka",
        "Nepal",
        "Afghanistan",
        "Kazakhstan",
        "Uzbekistan",
        "Turkmenistan",
        "Tajikistan",
        "Kyrgyzstan",
        "Mongolia",
        "Bhutan",
        "Maldives",
        "Laos",
        "Cambodia",
        "Brunei",
        "Timor-Leste",
        "Iran",
        "Iraq",
        "Saudi Arabia",
        "United Arab Emirates",
        "Qatar",
        "Bahrain",
        "Kuwait",
        "Oman",
        "Yemen",
        "Lebanon",
        "Syria",
        "Jordan",
        "Israel",
        "Armenia",
        "Azerbaijan",
        "Georgia",
        "Other",
    },
    "Oceania": {
        "Australia",
        "New Zealand",
        "Fiji",
        "Papua New Guinea",
        "Samoa",
        "Tonga",
        "Vanuatu",
        "Solomon Islands",
        "Kiribati",
        "Tuvalu",
        "Palau",
        "Micronesia",
        "Nauru",
        "Marshall Islands",
    },
}


class Command(BaseCommand):
    help = "Populate the CountryToContinent model with predefined data"

    def handle(self, *args, **kwargs):
        countries_to_create = [
            CountryToContinent(country=country, continent=continent)
            for continent, countries in COUNTRIES_BY_CONTINENT.items()
            for country in countries
        ]

        # Bulk insert and avoid duplicates
        CountryToContinent.objects.bulk_create(
            countries_to_create, ignore_conflicts=True
        )

        self.stdout.write(self.style.SUCCESS("Data populated successfully!"))
